version: '3.8'

services:
  postgres:
    image: ankane/pgvector:latest # pgvector가 포함된 Postgres 이미지
    container_name: fiery_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fiery_auth # 초기 DB (Auth용)
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
