// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: signaling/signaling.proto

package signaling

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 시그널링 메시지 유형
type SignalType int32

const (
	SignalType_UNKNOWN       SignalType = 0
	SignalType_OFFER         SignalType = 1 // SDP Offer
	SignalType_ANSWER        SignalType = 2 // SDP Answer
	SignalType_ICE_CANDIDATE SignalType = 3 // ICE Candidate
	SignalType_JOIN          SignalType = 4 // 방 입장 / 피어 연결 요청
	SignalType_LEAVE         SignalType = 5 // 연결 종료
	SignalType_PRESENCE      SignalType = 6 // 상태 업데이트 (Online/Offline)
	SignalType_INVITE        SignalType = 7 // 채팅방 초대
)

// Enum value maps for SignalType.
var (
	SignalType_name = map[int32]string{
		0: "UNKNOWN",
		1: "OFFER",
		2: "ANSWER",
		3: "ICE_CANDIDATE",
		4: "JOIN",
		5: "LEAVE",
		6: "PRESENCE",
		7: "INVITE",
	}
	SignalType_value = map[string]int32{
		"UNKNOWN":       0,
		"OFFER":         1,
		"ANSWER":        2,
		"ICE_CANDIDATE": 3,
		"JOIN":          4,
		"LEAVE":         5,
		"PRESENCE":      6,
		"INVITE":        7,
	}
)

func (x SignalType) Enum() *SignalType {
	p := new(SignalType)
	*p = x
	return p
}

func (x SignalType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignalType) Descriptor() protoreflect.EnumDescriptor {
	return file_signaling_signaling_proto_enumTypes[0].Descriptor()
}

func (SignalType) Type() protoreflect.EnumType {
	return &file_signaling_signaling_proto_enumTypes[0]
}

func (x SignalType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignalType.Descriptor instead.
func (SignalType) EnumDescriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{0}
}

// 시그널링 요청 메시지
type SignalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          SignalType             `protobuf:"varint,1,opt,name=type,proto3,enum=signaling.SignalType" json:"type,omitempty"`            // 메시지 유형
	TargetPeerId  string                 `protobuf:"bytes,2,opt,name=target_peer_id,json=targetPeerId,proto3" json:"target_peer_id,omitempty"` // 대상 피어 ID (1:1 통신 시)
	Sdp           string                 `protobuf:"bytes,3,opt,name=sdp,proto3" json:"sdp,omitempty"`                                         // SDP 정보 (Offer/Answer 인 경우)
	IceCandidate  string                 `protobuf:"bytes,4,opt,name=ice_candidate,json=iceCandidate,proto3" json:"ice_candidate,omitempty"`   // ICE Candidate 정보 (JSON string 등)
	RoomId        string                 `protobuf:"bytes,5,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                     // 채팅방 ID (INVITE, JOIN 등)
	Participants  []string               `protobuf:"bytes,6,rep,name=participants,proto3" json:"participants,omitempty"`                       // 참여자 ID 목록 (INVITE 시)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalRequest) Reset() {
	*x = SignalRequest{}
	mi := &file_signaling_signaling_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalRequest) ProtoMessage() {}

func (x *SignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_signaling_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalRequest.ProtoReflect.Descriptor instead.
func (*SignalRequest) Descriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{0}
}

func (x *SignalRequest) GetType() SignalType {
	if x != nil {
		return x.Type
	}
	return SignalType_UNKNOWN
}

func (x *SignalRequest) GetTargetPeerId() string {
	if x != nil {
		return x.TargetPeerId
	}
	return ""
}

func (x *SignalRequest) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

func (x *SignalRequest) GetIceCandidate() string {
	if x != nil {
		return x.IceCandidate
	}
	return ""
}

func (x *SignalRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SignalRequest) GetParticipants() []string {
	if x != nil {
		return x.Participants
	}
	return nil
}

// 시그널링 응답 메시지 (상대방으로부터 수신)
type SignalResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           SignalType             `protobuf:"varint,1,opt,name=type,proto3,enum=signaling.SignalType" json:"type,omitempty"`
	SourcePeerId   string                 `protobuf:"bytes,2,opt,name=source_peer_id,json=sourcePeerId,proto3" json:"source_peer_id,omitempty"` // 보낸 피어 ID
	Sdp            string                 `protobuf:"bytes,3,opt,name=sdp,proto3" json:"sdp,omitempty"`
	IceCandidate   string                 `protobuf:"bytes,4,opt,name=ice_candidate,json=iceCandidate,proto3" json:"ice_candidate,omitempty"`
	PresenceStatus string                 `protobuf:"bytes,5,opt,name=presence_status,json=presenceStatus,proto3" json:"presence_status,omitempty"` // "online" | "offline"
	RoomId         string                 `protobuf:"bytes,6,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Participants   []string               `protobuf:"bytes,7,rep,name=participants,proto3" json:"participants,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SignalResponse) Reset() {
	*x = SignalResponse{}
	mi := &file_signaling_signaling_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalResponse) ProtoMessage() {}

func (x *SignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_signaling_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalResponse.ProtoReflect.Descriptor instead.
func (*SignalResponse) Descriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{1}
}

func (x *SignalResponse) GetType() SignalType {
	if x != nil {
		return x.Type
	}
	return SignalType_UNKNOWN
}

func (x *SignalResponse) GetSourcePeerId() string {
	if x != nil {
		return x.SourcePeerId
	}
	return ""
}

func (x *SignalResponse) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

func (x *SignalResponse) GetIceCandidate() string {
	if x != nil {
		return x.IceCandidate
	}
	return ""
}

func (x *SignalResponse) GetPresenceStatus() string {
	if x != nil {
		return x.PresenceStatus
	}
	return ""
}

func (x *SignalResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SignalResponse) GetParticipants() []string {
	if x != nil {
		return x.Participants
	}
	return nil
}

var File_signaling_signaling_proto protoreflect.FileDescriptor

const file_signaling_signaling_proto_rawDesc = "" +
	"\n" +
	"\x19signaling/signaling.proto\x12\tsignaling\"\xd4\x01\n" +
	"\rSignalRequest\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.signaling.SignalTypeR\x04type\x12$\n" +
	"\x0etarget_peer_id\x18\x02 \x01(\tR\ftargetPeerId\x12\x10\n" +
	"\x03sdp\x18\x03 \x01(\tR\x03sdp\x12#\n" +
	"\rice_candidate\x18\x04 \x01(\tR\ficeCandidate\x12\x17\n" +
	"\aroom_id\x18\x05 \x01(\tR\x06roomId\x12\"\n" +
	"\fparticipants\x18\x06 \x03(\tR\fparticipants\"\xfe\x01\n" +
	"\x0eSignalResponse\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.signaling.SignalTypeR\x04type\x12$\n" +
	"\x0esource_peer_id\x18\x02 \x01(\tR\fsourcePeerId\x12\x10\n" +
	"\x03sdp\x18\x03 \x01(\tR\x03sdp\x12#\n" +
	"\rice_candidate\x18\x04 \x01(\tR\ficeCandidate\x12'\n" +
	"\x0fpresence_status\x18\x05 \x01(\tR\x0epresenceStatus\x12\x17\n" +
	"\aroom_id\x18\x06 \x01(\tR\x06roomId\x12\"\n" +
	"\fparticipants\x18\a \x03(\tR\fparticipants*r\n" +
	"\n" +
	"SignalType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05OFFER\x10\x01\x12\n" +
	"\n" +
	"\x06ANSWER\x10\x02\x12\x11\n" +
	"\rICE_CANDIDATE\x10\x03\x12\b\n" +
	"\x04JOIN\x10\x04\x12\t\n" +
	"\x05LEAVE\x10\x05\x12\f\n" +
	"\bPRESENCE\x10\x06\x12\n" +
	"\n" +
	"\x06INVITE\x10\a2\\\n" +
	"\x10SignalingService\x12H\n" +
	"\rStreamSignals\x12\x18.signaling.SignalRequest\x1a\x19.signaling.SignalResponse(\x010\x01B\x1aZ\x18server/.protos/signalingb\x06proto3"

var (
	file_signaling_signaling_proto_rawDescOnce sync.Once
	file_signaling_signaling_proto_rawDescData []byte
)

func file_signaling_signaling_proto_rawDescGZIP() []byte {
	file_signaling_signaling_proto_rawDescOnce.Do(func() {
		file_signaling_signaling_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_signaling_signaling_proto_rawDesc), len(file_signaling_signaling_proto_rawDesc)))
	})
	return file_signaling_signaling_proto_rawDescData
}

var file_signaling_signaling_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_signaling_signaling_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_signaling_signaling_proto_goTypes = []any{
	(SignalType)(0),        // 0: signaling.SignalType
	(*SignalRequest)(nil),  // 1: signaling.SignalRequest
	(*SignalResponse)(nil), // 2: signaling.SignalResponse
}
var file_signaling_signaling_proto_depIdxs = []int32{
	0, // 0: signaling.SignalRequest.type:type_name -> signaling.SignalType
	0, // 1: signaling.SignalResponse.type:type_name -> signaling.SignalType
	1, // 2: signaling.SignalingService.StreamSignals:input_type -> signaling.SignalRequest
	2, // 3: signaling.SignalingService.StreamSignals:output_type -> signaling.SignalResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_signaling_signaling_proto_init() }
func file_signaling_signaling_proto_init() {
	if File_signaling_signaling_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_signaling_signaling_proto_rawDesc), len(file_signaling_signaling_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_signaling_signaling_proto_goTypes,
		DependencyIndexes: file_signaling_signaling_proto_depIdxs,
		EnumInfos:         file_signaling_signaling_proto_enumTypes,
		MessageInfos:      file_signaling_signaling_proto_msgTypes,
	}.Build()
	File_signaling_signaling_proto = out.File
	file_signaling_signaling_proto_goTypes = nil
	file_signaling_signaling_proto_depIdxs = nil
}
