// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: auth/acl.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enums
type AccessLevel int32

const (
	AccessLevel_ACCESS_LEVEL_UNSPECIFIED AccessLevel = 0
	AccessLevel_ACCESS_LEVEL_SUMMARY     AccessLevel = 1 // Metadata only
	AccessLevel_ACCESS_LEVEL_PARTIAL     AccessLevel = 2 // Summary + Key Facts
	AccessLevel_ACCESS_LEVEL_FULL        AccessLevel = 3 // Full Content
)

// Enum value maps for AccessLevel.
var (
	AccessLevel_name = map[int32]string{
		0: "ACCESS_LEVEL_UNSPECIFIED",
		1: "ACCESS_LEVEL_SUMMARY",
		2: "ACCESS_LEVEL_PARTIAL",
		3: "ACCESS_LEVEL_FULL",
	}
	AccessLevel_value = map[string]int32{
		"ACCESS_LEVEL_UNSPECIFIED": 0,
		"ACCESS_LEVEL_SUMMARY":     1,
		"ACCESS_LEVEL_PARTIAL":     2,
		"ACCESS_LEVEL_FULL":        3,
	}
)

func (x AccessLevel) Enum() *AccessLevel {
	p := new(AccessLevel)
	*p = x
	return p
}

func (x AccessLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_acl_proto_enumTypes[0].Descriptor()
}

func (AccessLevel) Type() protoreflect.EnumType {
	return &file_auth_acl_proto_enumTypes[0]
}

func (x AccessLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessLevel.Descriptor instead.
func (AccessLevel) EnumDescriptor() ([]byte, []int) {
	return file_auth_acl_proto_rawDescGZIP(), []int{0}
}

type AccessRequestStatus int32

const (
	AccessRequestStatus_ACCESS_REQUEST_STATUS_UNSPECIFIED AccessRequestStatus = 0
	AccessRequestStatus_ACCESS_REQUEST_STATUS_PENDING     AccessRequestStatus = 1
	AccessRequestStatus_ACCESS_REQUEST_STATUS_APPROVED    AccessRequestStatus = 2
	AccessRequestStatus_ACCESS_REQUEST_STATUS_REJECTED    AccessRequestStatus = 3
)

// Enum value maps for AccessRequestStatus.
var (
	AccessRequestStatus_name = map[int32]string{
		0: "ACCESS_REQUEST_STATUS_UNSPECIFIED",
		1: "ACCESS_REQUEST_STATUS_PENDING",
		2: "ACCESS_REQUEST_STATUS_APPROVED",
		3: "ACCESS_REQUEST_STATUS_REJECTED",
	}
	AccessRequestStatus_value = map[string]int32{
		"ACCESS_REQUEST_STATUS_UNSPECIFIED": 0,
		"ACCESS_REQUEST_STATUS_PENDING":     1,
		"ACCESS_REQUEST_STATUS_APPROVED":    2,
		"ACCESS_REQUEST_STATUS_REJECTED":    3,
	}
)

func (x AccessRequestStatus) Enum() *AccessRequestStatus {
	p := new(AccessRequestStatus)
	*p = x
	return p
}

func (x AccessRequestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessRequestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_acl_proto_enumTypes[1].Descriptor()
}

func (AccessRequestStatus) Type() protoreflect.EnumType {
	return &file_auth_acl_proto_enumTypes[1]
}

func (x AccessRequestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessRequestStatus.Descriptor instead.
func (AccessRequestStatus) EnumDescriptor() ([]byte, []int) {
	return file_auth_acl_proto_rawDescGZIP(), []int{1}
}

type DocumentState int32

const (
	DocumentState_DOCUMENT_STATE_UNSPECIFIED DocumentState = 0
	DocumentState_DOCUMENT_STATE_DRAFT       DocumentState = 1
	DocumentState_DOCUMENT_STATE_FEEDBACK    DocumentState = 2
	DocumentState_DOCUMENT_STATE_PUBLISHED   DocumentState = 3
)

// Enum value maps for DocumentState.
var (
	DocumentState_name = map[int32]string{
		0: "DOCUMENT_STATE_UNSPECIFIED",
		1: "DOCUMENT_STATE_DRAFT",
		2: "DOCUMENT_STATE_FEEDBACK",
		3: "DOCUMENT_STATE_PUBLISHED",
	}
	DocumentState_value = map[string]int32{
		"DOCUMENT_STATE_UNSPECIFIED": 0,
		"DOCUMENT_STATE_DRAFT":       1,
		"DOCUMENT_STATE_FEEDBACK":    2,
		"DOCUMENT_STATE_PUBLISHED":   3,
	}
)

func (x DocumentState) Enum() *DocumentState {
	p := new(DocumentState)
	*p = x
	return p
}

func (x DocumentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DocumentState) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_acl_proto_enumTypes[2].Descriptor()
}

func (DocumentState) Type() protoreflect.EnumType {
	return &file_auth_acl_proto_enumTypes[2]
}

func (x DocumentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DocumentState.Descriptor instead.
func (DocumentState) EnumDescriptor() ([]byte, []int) {
	return file_auth_acl_proto_rawDescGZIP(), []int{2}
}

// VisibilityLevel Enum (Moved from document.proto)
type VisibilityLevel int32

const (
	VisibilityLevel_VISIBILITY_LEVEL_UNSPECIFIED VisibilityLevel = 0
	VisibilityLevel_VISIBILITY_LEVEL_HIDDEN      VisibilityLevel = 1 // No external visibility
	VisibilityLevel_VISIBILITY_LEVEL_METADATA    VisibilityLevel = 2 // Only metadata visible
	VisibilityLevel_VISIBILITY_LEVEL_SNIPPET     VisibilityLevel = 3 // Summary/Snippet visible
	VisibilityLevel_VISIBILITY_LEVEL_PUBLIC      VisibilityLevel = 4 // Full content visible
)

// Enum value maps for VisibilityLevel.
var (
	VisibilityLevel_name = map[int32]string{
		0: "VISIBILITY_LEVEL_UNSPECIFIED",
		1: "VISIBILITY_LEVEL_HIDDEN",
		2: "VISIBILITY_LEVEL_METADATA",
		3: "VISIBILITY_LEVEL_SNIPPET",
		4: "VISIBILITY_LEVEL_PUBLIC",
	}
	VisibilityLevel_value = map[string]int32{
		"VISIBILITY_LEVEL_UNSPECIFIED": 0,
		"VISIBILITY_LEVEL_HIDDEN":      1,
		"VISIBILITY_LEVEL_METADATA":    2,
		"VISIBILITY_LEVEL_SNIPPET":     3,
		"VISIBILITY_LEVEL_PUBLIC":      4,
	}
)

func (x VisibilityLevel) Enum() *VisibilityLevel {
	p := new(VisibilityLevel)
	*p = x
	return p
}

func (x VisibilityLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VisibilityLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_acl_proto_enumTypes[3].Descriptor()
}

func (VisibilityLevel) Type() protoreflect.EnumType {
	return &file_auth_acl_proto_enumTypes[3]
}

func (x VisibilityLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VisibilityLevel.Descriptor instead.
func (VisibilityLevel) EnumDescriptor() ([]byte, []int) {
	return file_auth_acl_proto_rawDescGZIP(), []int{3}
}

// Messages
type Permission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccessLevel   AccessLevel            `protobuf:"varint,4,opt,name=access_level,json=accessLevel,proto3,enum=auth.AccessLevel" json:"access_level,omitempty"`
	GrantedAt     string                 `protobuf:"bytes,5,opt,name=granted_at,json=grantedAt,proto3" json:"granted_at,omitempty"`
	GrantedBy     string                 `protobuf:"bytes,6,opt,name=granted_by,json=grantedBy,proto3" json:"granted_by,omitempty"` // User ID of the granter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_auth_acl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_auth_acl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_auth_acl_proto_rawDescGZIP(), []int{0}
}

func (x *Permission) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Permission) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *Permission) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Permission) GetAccessLevel() AccessLevel {
	if x != nil {
		return x.AccessLevel
	}
	return AccessLevel_ACCESS_LEVEL_UNSPECIFIED
}

func (x *Permission) GetGrantedAt() string {
	if x != nil {
		return x.GrantedAt
	}
	return ""
}

func (x *Permission) GetGrantedBy() string {
	if x != nil {
		return x.GrantedBy
	}
	return ""
}

type AccessRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RequesterId    string                 `protobuf:"bytes,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	DocumentId     string                 `protobuf:"bytes,3,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	RequestedLevel AccessLevel            `protobuf:"varint,4,opt,name=requested_level,json=requestedLevel,proto3,enum=auth.AccessLevel" json:"requested_level,omitempty"`
	Status         AccessRequestStatus    `protobuf:"varint,5,opt,name=status,proto3,enum=auth.AccessRequestStatus" json:"status,omitempty"`
	OwnerId        string                 `protobuf:"bytes,6,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Expanded
	Requester     *User `protobuf:"bytes,9,opt,name=requester,proto3" json:"requester,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessRequest) Reset() {
	*x = AccessRequest{}
	mi := &file_auth_acl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessRequest) ProtoMessage() {}

func (x *AccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_acl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessRequest.ProtoReflect.Descriptor instead.
func (*AccessRequest) Descriptor() ([]byte, []int) {
	return file_auth_acl_proto_rawDescGZIP(), []int{1}
}

func (x *AccessRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccessRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *AccessRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *AccessRequest) GetRequestedLevel() AccessLevel {
	if x != nil {
		return x.RequestedLevel
	}
	return AccessLevel_ACCESS_LEVEL_UNSPECIFIED
}

func (x *AccessRequest) GetStatus() AccessRequestStatus {
	if x != nil {
		return x.Status
	}
	return AccessRequestStatus_ACCESS_REQUEST_STATUS_UNSPECIFIED
}

func (x *AccessRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *AccessRequest) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AccessRequest) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *AccessRequest) GetRequester() *User {
	if x != nil {
		return x.Requester
	}
	return nil
}

// CheckAccess
type CheckAccessRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	UserId     string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DocumentId string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	TenantId   string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Attributes for Policy Engine
	UserDepartmentId     string        `protobuf:"bytes,4,opt,name=user_department_id,json=userDepartmentId,proto3" json:"user_department_id,omitempty"`
	DocumentDepartmentId string        `protobuf:"bytes,5,opt,name=document_department_id,json=documentDepartmentId,proto3" json:"document_department_id,omitempty"`
	DocumentOwnerId      string        `protobuf:"bytes,6,opt,name=document_owner_id,json=documentOwnerId,proto3" json:"document_owner_id,omitempty"`
	DocumentState        DocumentState `protobuf:"varint,7,opt,name=document_state,json=documentState,proto3,enum=auth.DocumentState" json:"document_state,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CheckAccessRequest) Reset() {
	*x = CheckAccessRequest{}
	mi := &file_auth_acl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessRequest) ProtoMessage() {}

func (x *CheckAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_acl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessRequest.ProtoReflect.Descriptor instead.
func (*CheckAccessRequest) Descriptor() ([]byte, []int) {
	return file_auth_acl_proto_rawDescGZIP(), []int{2}
}

func (x *CheckAccessRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckAccessRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *CheckAccessRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CheckAccessRequest) GetUserDepartmentId() string {
	if x != nil {
		return x.UserDepartmentId
	}
	return ""
}

func (x *CheckAccessRequest) GetDocumentDepartmentId() string {
	if x != nil {
		return x.DocumentDepartmentId
	}
	return ""
}

func (x *CheckAccessRequest) GetDocumentOwnerId() string {
	if x != nil {
		return x.DocumentOwnerId
	}
	return ""
}

func (x *CheckAccessRequest) GetDocumentState() DocumentState {
	if x != nil {
		return x.DocumentState
	}
	return DocumentState_DOCUMENT_STATE_UNSPECIFIED
}

type CheckAccessResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Allowed        bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	MaxAccessLevel AccessLevel            `protobuf:"varint,2,opt,name=max_access_level,json=maxAccessLevel,proto3,enum=auth.AccessLevel" json:"max_access_level,omitempty"`
	Reason         string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckAccessResponse) Reset() {
	*x = CheckAccessResponse{}
	mi := &file_auth_acl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessResponse) ProtoMessage() {}

func (x *CheckAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_acl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessResponse.ProtoReflect.Descriptor instead.
func (*CheckAccessResponse) Descriptor() ([]byte, []int) {
	return file_auth_acl_proto_rawDescGZIP(), []int{3}
}

func (x *CheckAccessResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckAccessResponse) GetMaxAccessLevel() AccessLevel {
	if x != nil {
		return x.MaxAccessLevel
	}
	return AccessLevel_ACCESS_LEVEL_UNSPECIFIED
}

func (x *CheckAccessResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// RequestAccess
type RequestAccessRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequesterId    string                 `protobuf:"bytes,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	DocumentId     string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	RequestedLevel AccessLevel            `protobuf:"varint,3,opt,name=requested_level,json=requestedLevel,proto3,enum=auth.AccessLevel" json:"requested_level,omitempty"`
	OwnerId        string                 `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"` // Used to route the request
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RequestAccessRequest) Reset() {
	*x = RequestAccessRequest{}
	mi := &file_auth_acl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAccessRequest) ProtoMessage() {}

func (x *RequestAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_acl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAccessRequest.ProtoReflect.Descriptor instead.
func (*RequestAccessRequest) Descriptor() ([]byte, []int) {
	return file_auth_acl_proto_rawDescGZIP(), []int{4}
}

func (x *RequestAccessRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *RequestAccessRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *RequestAccessRequest) GetRequestedLevel() AccessLevel {
	if x != nil {
		return x.RequestedLevel
	}
	return AccessLevel_ACCESS_LEVEL_UNSPECIFIED
}

func (x *RequestAccessRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type RequestAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        AccessRequestStatus    `protobuf:"varint,2,opt,name=status,proto3,enum=auth.AccessRequestStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestAccessResponse) Reset() {
	*x = RequestAccessResponse{}
	mi := &file_auth_acl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAccessResponse) ProtoMessage() {}

func (x *RequestAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_acl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAccessResponse.ProtoReflect.Descriptor instead.
func (*RequestAccessResponse) Descriptor() ([]byte, []int) {
	return file_auth_acl_proto_rawDescGZIP(), []int{5}
}

func (x *RequestAccessResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestAccessResponse) GetStatus() AccessRequestStatus {
	if x != nil {
		return x.Status
	}
	return AccessRequestStatus_ACCESS_REQUEST_STATUS_UNSPECIFIED
}

// GrantAccess (Approve/Reject)
type GrantAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ReviewerId    string                 `protobuf:"bytes,2,opt,name=reviewer_id,json=reviewerId,proto3" json:"reviewer_id,omitempty"`
	Status        AccessRequestStatus    `protobuf:"varint,3,opt,name=status,proto3,enum=auth.AccessRequestStatus" json:"status,omitempty"`                         // APPROVED or REJECTED
	GrantedLevel  AccessLevel            `protobuf:"varint,4,opt,name=granted_level,json=grantedLevel,proto3,enum=auth.AccessLevel" json:"granted_level,omitempty"` // Can be different from requested
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantAccessRequest) Reset() {
	*x = GrantAccessRequest{}
	mi := &file_auth_acl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantAccessRequest) ProtoMessage() {}

func (x *GrantAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_acl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantAccessRequest.ProtoReflect.Descriptor instead.
func (*GrantAccessRequest) Descriptor() ([]byte, []int) {
	return file_auth_acl_proto_rawDescGZIP(), []int{6}
}

func (x *GrantAccessRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GrantAccessRequest) GetReviewerId() string {
	if x != nil {
		return x.ReviewerId
	}
	return ""
}

func (x *GrantAccessRequest) GetStatus() AccessRequestStatus {
	if x != nil {
		return x.Status
	}
	return AccessRequestStatus_ACCESS_REQUEST_STATUS_UNSPECIFIED
}

func (x *GrantAccessRequest) GetGrantedLevel() AccessLevel {
	if x != nil {
		return x.GrantedLevel
	}
	return AccessLevel_ACCESS_LEVEL_UNSPECIFIED
}

type GrantAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Permission    *Permission            `protobuf:"bytes,2,opt,name=permission,proto3" json:"permission,omitempty"` // Populated if approved
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantAccessResponse) Reset() {
	*x = GrantAccessResponse{}
	mi := &file_auth_acl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantAccessResponse) ProtoMessage() {}

func (x *GrantAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_acl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantAccessResponse.ProtoReflect.Descriptor instead.
func (*GrantAccessResponse) Descriptor() ([]byte, []int) {
	return file_auth_acl_proto_rawDescGZIP(), []int{7}
}

func (x *GrantAccessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GrantAccessResponse) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

// ListAccessRequests
type ListAccessRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`              // Requester or Owner
	AsReviewer    bool                   `protobuf:"varint,2,opt,name=as_reviewer,json=asReviewer,proto3" json:"as_reviewer,omitempty"` // If true, list requests where user_id is owner
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccessRequestsRequest) Reset() {
	*x = ListAccessRequestsRequest{}
	mi := &file_auth_acl_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccessRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessRequestsRequest) ProtoMessage() {}

func (x *ListAccessRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_acl_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessRequestsRequest.ProtoReflect.Descriptor instead.
func (*ListAccessRequestsRequest) Descriptor() ([]byte, []int) {
	return file_auth_acl_proto_rawDescGZIP(), []int{8}
}

func (x *ListAccessRequestsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListAccessRequestsRequest) GetAsReviewer() bool {
	if x != nil {
		return x.AsReviewer
	}
	return false
}

func (x *ListAccessRequestsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ListAccessRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*AccessRequest       `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccessRequestsResponse) Reset() {
	*x = ListAccessRequestsResponse{}
	mi := &file_auth_acl_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccessRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessRequestsResponse) ProtoMessage() {}

func (x *ListAccessRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_acl_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessRequestsResponse.ProtoReflect.Descriptor instead.
func (*ListAccessRequestsResponse) Descriptor() ([]byte, []int) {
	return file_auth_acl_proto_rawDescGZIP(), []int{9}
}

func (x *ListAccessRequestsResponse) GetRequests() []*AccessRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

// Visibility Approval Messages
type VisibilityApproval struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DocumentId     string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	RequesterId    string                 `protobuf:"bytes,3,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	ApproverId     string                 `protobuf:"bytes,4,opt,name=approver_id,json=approverId,proto3" json:"approver_id,omitempty"`
	RequestedLevel int32                  `protobuf:"varint,5,opt,name=requested_level,json=requestedLevel,proto3" json:"requested_level,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // pending, approved, rejected
	CreatedAt      string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VisibilityApproval) Reset() {
	*x = VisibilityApproval{}
	mi := &file_auth_acl_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisibilityApproval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisibilityApproval) ProtoMessage() {}

func (x *VisibilityApproval) ProtoReflect() protoreflect.Message {
	mi := &file_auth_acl_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisibilityApproval.ProtoReflect.Descriptor instead.
func (*VisibilityApproval) Descriptor() ([]byte, []int) {
	return file_auth_acl_proto_rawDescGZIP(), []int{10}
}

func (x *VisibilityApproval) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VisibilityApproval) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *VisibilityApproval) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *VisibilityApproval) GetApproverId() string {
	if x != nil {
		return x.ApproverId
	}
	return ""
}

func (x *VisibilityApproval) GetRequestedLevel() int32 {
	if x != nil {
		return x.RequestedLevel
	}
	return 0
}

func (x *VisibilityApproval) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VisibilityApproval) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *VisibilityApproval) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListVisibilityApprovalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApproverId    string                 `protobuf:"bytes,1,opt,name=approver_id,json=approverId,proto3" json:"approver_id,omitempty"`       // Manager ID
	DepartmentId  string                 `protobuf:"bytes,2,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"` // Filter by Dept
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVisibilityApprovalsRequest) Reset() {
	*x = ListVisibilityApprovalsRequest{}
	mi := &file_auth_acl_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVisibilityApprovalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVisibilityApprovalsRequest) ProtoMessage() {}

func (x *ListVisibilityApprovalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_acl_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVisibilityApprovalsRequest.ProtoReflect.Descriptor instead.
func (*ListVisibilityApprovalsRequest) Descriptor() ([]byte, []int) {
	return file_auth_acl_proto_rawDescGZIP(), []int{11}
}

func (x *ListVisibilityApprovalsRequest) GetApproverId() string {
	if x != nil {
		return x.ApproverId
	}
	return ""
}

func (x *ListVisibilityApprovalsRequest) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

func (x *ListVisibilityApprovalsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ListVisibilityApprovalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Approvals     []*VisibilityApproval  `protobuf:"bytes,1,rep,name=approvals,proto3" json:"approvals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVisibilityApprovalsResponse) Reset() {
	*x = ListVisibilityApprovalsResponse{}
	mi := &file_auth_acl_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVisibilityApprovalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVisibilityApprovalsResponse) ProtoMessage() {}

func (x *ListVisibilityApprovalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_acl_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVisibilityApprovalsResponse.ProtoReflect.Descriptor instead.
func (*ListVisibilityApprovalsResponse) Descriptor() ([]byte, []int) {
	return file_auth_acl_proto_rawDescGZIP(), []int{12}
}

func (x *ListVisibilityApprovalsResponse) GetApprovals() []*VisibilityApproval {
	if x != nil {
		return x.Approvals
	}
	return nil
}

type ApproveVisibilityChangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApprovalId    string                 `protobuf:"bytes,1,opt,name=approval_id,json=approvalId,proto3" json:"approval_id,omitempty"`
	ApproverId    string                 `protobuf:"bytes,2,opt,name=approver_id,json=approverId,proto3" json:"approver_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // approved, rejected
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveVisibilityChangeRequest) Reset() {
	*x = ApproveVisibilityChangeRequest{}
	mi := &file_auth_acl_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveVisibilityChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveVisibilityChangeRequest) ProtoMessage() {}

func (x *ApproveVisibilityChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_acl_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveVisibilityChangeRequest.ProtoReflect.Descriptor instead.
func (*ApproveVisibilityChangeRequest) Descriptor() ([]byte, []int) {
	return file_auth_acl_proto_rawDescGZIP(), []int{13}
}

func (x *ApproveVisibilityChangeRequest) GetApprovalId() string {
	if x != nil {
		return x.ApprovalId
	}
	return ""
}

func (x *ApproveVisibilityChangeRequest) GetApproverId() string {
	if x != nil {
		return x.ApproverId
	}
	return ""
}

func (x *ApproveVisibilityChangeRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ApproveVisibilityChangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveVisibilityChangeResponse) Reset() {
	*x = ApproveVisibilityChangeResponse{}
	mi := &file_auth_acl_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveVisibilityChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveVisibilityChangeResponse) ProtoMessage() {}

func (x *ApproveVisibilityChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_acl_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveVisibilityChangeResponse.ProtoReflect.Descriptor instead.
func (*ApproveVisibilityChangeResponse) Descriptor() ([]byte, []int) {
	return file_auth_acl_proto_rawDescGZIP(), []int{14}
}

func (x *ApproveVisibilityChangeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_auth_acl_proto protoreflect.FileDescriptor

const file_auth_acl_proto_rawDesc = "" +
	"\n" +
	"\x0eauth/acl.proto\x12\x04auth\x1a\x0fauth/user.proto\"\xca\x01\n" +
	"\n" +
	"Permission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x124\n" +
	"\faccess_level\x18\x04 \x01(\x0e2\x11.auth.AccessLevelR\vaccessLevel\x12\x1d\n" +
	"\n" +
	"granted_at\x18\x05 \x01(\tR\tgrantedAt\x12\x1d\n" +
	"\n" +
	"granted_by\x18\x06 \x01(\tR\tgrantedBy\"\xd5\x02\n" +
	"\rAccessRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\frequester_id\x18\x02 \x01(\tR\vrequesterId\x12\x1f\n" +
	"\vdocument_id\x18\x03 \x01(\tR\n" +
	"documentId\x12:\n" +
	"\x0frequested_level\x18\x04 \x01(\x0e2\x11.auth.AccessLevelR\x0erequestedLevel\x121\n" +
	"\x06status\x18\x05 \x01(\x0e2\x19.auth.AccessRequestStatusR\x06status\x12\x19\n" +
	"\bowner_id\x18\x06 \x01(\tR\aownerId\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x12(\n" +
	"\trequester\x18\t \x01(\v2\n" +
	".auth.UserR\trequester\"\xb7\x02\n" +
	"\x12CheckAccessRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12,\n" +
	"\x12user_department_id\x18\x04 \x01(\tR\x10userDepartmentId\x124\n" +
	"\x16document_department_id\x18\x05 \x01(\tR\x14documentDepartmentId\x12*\n" +
	"\x11document_owner_id\x18\x06 \x01(\tR\x0fdocumentOwnerId\x12:\n" +
	"\x0edocument_state\x18\a \x01(\x0e2\x13.auth.DocumentStateR\rdocumentState\"\x84\x01\n" +
	"\x13CheckAccessResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12;\n" +
	"\x10max_access_level\x18\x02 \x01(\x0e2\x11.auth.AccessLevelR\x0emaxAccessLevel\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xb1\x01\n" +
	"\x14RequestAccessRequest\x12!\n" +
	"\frequester_id\x18\x01 \x01(\tR\vrequesterId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12:\n" +
	"\x0frequested_level\x18\x03 \x01(\x0e2\x11.auth.AccessLevelR\x0erequestedLevel\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\tR\aownerId\"i\n" +
	"\x15RequestAccessResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.auth.AccessRequestStatusR\x06status\"\xbf\x01\n" +
	"\x12GrantAccessRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vreviewer_id\x18\x02 \x01(\tR\n" +
	"reviewerId\x121\n" +
	"\x06status\x18\x03 \x01(\x0e2\x19.auth.AccessRequestStatusR\x06status\x126\n" +
	"\rgranted_level\x18\x04 \x01(\x0e2\x11.auth.AccessLevelR\fgrantedLevel\"a\n" +
	"\x13GrantAccessResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x120\n" +
	"\n" +
	"permission\x18\x02 \x01(\v2\x10.auth.PermissionR\n" +
	"permission\"r\n" +
	"\x19ListAccessRequestsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vas_reviewer\x18\x02 \x01(\bR\n" +
	"asReviewer\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\"M\n" +
	"\x1aListAccessRequestsResponse\x12/\n" +
	"\brequests\x18\x01 \x03(\v2\x13.auth.AccessRequestR\brequests\"\x88\x02\n" +
	"\x12VisibilityApproval\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12!\n" +
	"\frequester_id\x18\x03 \x01(\tR\vrequesterId\x12\x1f\n" +
	"\vapprover_id\x18\x04 \x01(\tR\n" +
	"approverId\x12'\n" +
	"\x0frequested_level\x18\x05 \x01(\x05R\x0erequestedLevel\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"\x83\x01\n" +
	"\x1eListVisibilityApprovalsRequest\x12\x1f\n" +
	"\vapprover_id\x18\x01 \x01(\tR\n" +
	"approverId\x12#\n" +
	"\rdepartment_id\x18\x02 \x01(\tR\fdepartmentId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\"Y\n" +
	"\x1fListVisibilityApprovalsResponse\x126\n" +
	"\tapprovals\x18\x01 \x03(\v2\x18.auth.VisibilityApprovalR\tapprovals\"z\n" +
	"\x1eApproveVisibilityChangeRequest\x12\x1f\n" +
	"\vapproval_id\x18\x01 \x01(\tR\n" +
	"approvalId\x12\x1f\n" +
	"\vapprover_id\x18\x02 \x01(\tR\n" +
	"approverId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\";\n" +
	"\x1fApproveVisibilityChangeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*v\n" +
	"\vAccessLevel\x12\x1c\n" +
	"\x18ACCESS_LEVEL_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ACCESS_LEVEL_SUMMARY\x10\x01\x12\x18\n" +
	"\x14ACCESS_LEVEL_PARTIAL\x10\x02\x12\x15\n" +
	"\x11ACCESS_LEVEL_FULL\x10\x03*\xa7\x01\n" +
	"\x13AccessRequestStatus\x12%\n" +
	"!ACCESS_REQUEST_STATUS_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dACCESS_REQUEST_STATUS_PENDING\x10\x01\x12\"\n" +
	"\x1eACCESS_REQUEST_STATUS_APPROVED\x10\x02\x12\"\n" +
	"\x1eACCESS_REQUEST_STATUS_REJECTED\x10\x03*\x84\x01\n" +
	"\rDocumentState\x12\x1e\n" +
	"\x1aDOCUMENT_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14DOCUMENT_STATE_DRAFT\x10\x01\x12\x1b\n" +
	"\x17DOCUMENT_STATE_FEEDBACK\x10\x02\x12\x1c\n" +
	"\x18DOCUMENT_STATE_PUBLISHED\x10\x03*\xaa\x01\n" +
	"\x0fVisibilityLevel\x12 \n" +
	"\x1cVISIBILITY_LEVEL_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17VISIBILITY_LEVEL_HIDDEN\x10\x01\x12\x1d\n" +
	"\x19VISIBILITY_LEVEL_METADATA\x10\x02\x12\x1c\n" +
	"\x18VISIBILITY_LEVEL_SNIPPET\x10\x03\x12\x1b\n" +
	"\x17VISIBILITY_LEVEL_PUBLIC\x10\x04B\x15Z\x13server/.protos/authb\x06proto3"

var (
	file_auth_acl_proto_rawDescOnce sync.Once
	file_auth_acl_proto_rawDescData []byte
)

func file_auth_acl_proto_rawDescGZIP() []byte {
	file_auth_acl_proto_rawDescOnce.Do(func() {
		file_auth_acl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_acl_proto_rawDesc), len(file_auth_acl_proto_rawDesc)))
	})
	return file_auth_acl_proto_rawDescData
}

var file_auth_acl_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_auth_acl_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_auth_acl_proto_goTypes = []any{
	(AccessLevel)(0),                        // 0: auth.AccessLevel
	(AccessRequestStatus)(0),                // 1: auth.AccessRequestStatus
	(DocumentState)(0),                      // 2: auth.DocumentState
	(VisibilityLevel)(0),                    // 3: auth.VisibilityLevel
	(*Permission)(nil),                      // 4: auth.Permission
	(*AccessRequest)(nil),                   // 5: auth.AccessRequest
	(*CheckAccessRequest)(nil),              // 6: auth.CheckAccessRequest
	(*CheckAccessResponse)(nil),             // 7: auth.CheckAccessResponse
	(*RequestAccessRequest)(nil),            // 8: auth.RequestAccessRequest
	(*RequestAccessResponse)(nil),           // 9: auth.RequestAccessResponse
	(*GrantAccessRequest)(nil),              // 10: auth.GrantAccessRequest
	(*GrantAccessResponse)(nil),             // 11: auth.GrantAccessResponse
	(*ListAccessRequestsRequest)(nil),       // 12: auth.ListAccessRequestsRequest
	(*ListAccessRequestsResponse)(nil),      // 13: auth.ListAccessRequestsResponse
	(*VisibilityApproval)(nil),              // 14: auth.VisibilityApproval
	(*ListVisibilityApprovalsRequest)(nil),  // 15: auth.ListVisibilityApprovalsRequest
	(*ListVisibilityApprovalsResponse)(nil), // 16: auth.ListVisibilityApprovalsResponse
	(*ApproveVisibilityChangeRequest)(nil),  // 17: auth.ApproveVisibilityChangeRequest
	(*ApproveVisibilityChangeResponse)(nil), // 18: auth.ApproveVisibilityChangeResponse
	(*User)(nil),                            // 19: auth.User
}
var file_auth_acl_proto_depIdxs = []int32{
	0,  // 0: auth.Permission.access_level:type_name -> auth.AccessLevel
	0,  // 1: auth.AccessRequest.requested_level:type_name -> auth.AccessLevel
	1,  // 2: auth.AccessRequest.status:type_name -> auth.AccessRequestStatus
	19, // 3: auth.AccessRequest.requester:type_name -> auth.User
	2,  // 4: auth.CheckAccessRequest.document_state:type_name -> auth.DocumentState
	0,  // 5: auth.CheckAccessResponse.max_access_level:type_name -> auth.AccessLevel
	0,  // 6: auth.RequestAccessRequest.requested_level:type_name -> auth.AccessLevel
	1,  // 7: auth.RequestAccessResponse.status:type_name -> auth.AccessRequestStatus
	1,  // 8: auth.GrantAccessRequest.status:type_name -> auth.AccessRequestStatus
	0,  // 9: auth.GrantAccessRequest.granted_level:type_name -> auth.AccessLevel
	4,  // 10: auth.GrantAccessResponse.permission:type_name -> auth.Permission
	5,  // 11: auth.ListAccessRequestsResponse.requests:type_name -> auth.AccessRequest
	14, // 12: auth.ListVisibilityApprovalsResponse.approvals:type_name -> auth.VisibilityApproval
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_auth_acl_proto_init() }
func file_auth_acl_proto_init() {
	if File_auth_acl_proto != nil {
		return
	}
	file_auth_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_acl_proto_rawDesc), len(file_auth_acl_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_acl_proto_goTypes,
		DependencyIndexes: file_auth_acl_proto_depIdxs,
		EnumInfos:         file_auth_acl_proto_enumTypes,
		MessageInfos:      file_auth_acl_proto_msgTypes,
	}.Build()
	File_auth_acl_proto = out.File
	file_auth_acl_proto_goTypes = nil
	file_auth_acl_proto_depIdxs = nil
}
