// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: auth/auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 로그인 요청
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 로그인 응답
type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *LoginResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

// 토큰 검증 요청
type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_auth_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

// 토큰 검증 응답
type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserSalt      string                 `protobuf:"bytes,3,opt,name=user_salt,json=userSalt,proto3" json:"user_salt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_auth_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateTokenResponse) GetUserSalt() string {
	if x != nil {
		return x.UserSalt
	}
	return ""
}

// 리프레시 토큰 요청
type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_auth_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// 리프레시 토큰 응답
type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_auth_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

var File_auth_auth_proto protoreflect.FileDescriptor

const file_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x0fauth/auth.proto\x12\x04auth\x1a\x0fauth/user.proto\x1a\x11auth/tenant.proto\x1a\x0eauth/acl.proto\x1a\x15auth/department.proto\x1a\x12auth/project.proto\x1a\x13auth/document.proto\x1a\x13auth/position.proto\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x8a\x01\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"9\n" +
	"\x14ValidateTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"c\n" +
	"\x15ValidateTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_salt\x18\x03 \x01(\tR\buserSalt\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"^\n" +
	"\x14RefreshTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken2\x92\x19\n" +
	"\vAuthService\x120\n" +
	"\x05Login\x12\x12.auth.LoginRequest\x1a\x13.auth.LoginResponse\x12H\n" +
	"\rValidateToken\x12\x1a.auth.ValidateTokenRequest\x1a\x1b.auth.ValidateTokenResponse\x12E\n" +
	"\fRefreshToken\x12\x19.auth.RefreshTokenRequest\x1a\x1a.auth.RefreshTokenResponse\x12?\n" +
	"\n" +
	"CreateUser\x12\x17.auth.CreateUserRequest\x1a\x18.auth.CreateUserResponse\x12Q\n" +
	"\x10BatchCreateUsers\x12\x1d.auth.BatchCreateUsersRequest\x1a\x1e.auth.BatchCreateUsersResponse\x126\n" +
	"\aGetUser\x12\x14.auth.GetUserRequest\x1a\x15.auth.GetUserResponse\x12<\n" +
	"\tListUsers\x12\x16.auth.ListUsersRequest\x1a\x17.auth.ListUsersResponse\x12?\n" +
	"\n" +
	"UpdateUser\x12\x17.auth.UpdateUserRequest\x1a\x18.auth.UpdateUserResponse\x12?\n" +
	"\n" +
	"DeleteUser\x12\x17.auth.DeleteUserRequest\x1a\x18.auth.DeleteUserResponse\x12E\n" +
	"\fCreateTenant\x12\x19.auth.CreateTenantRequest\x1a\x1a.auth.CreateTenantResponse\x12<\n" +
	"\tGetTenant\x12\x16.auth.GetTenantRequest\x1a\x17.auth.GetTenantResponse\x12B\n" +
	"\vListTenants\x12\x18.auth.ListTenantsRequest\x1a\x19.auth.ListTenantsResponse\x12Q\n" +
	"\x10CreateDepartment\x12\x1d.auth.CreateDepartmentRequest\x1a\x1e.auth.CreateDepartmentResponse\x12c\n" +
	"\x16BatchCreateDepartments\x12#.auth.BatchCreateDepartmentsRequest\x1a$.auth.BatchCreateDepartmentsResponse\x12N\n" +
	"\x0fListDepartments\x12\x1c.auth.ListDepartmentsRequest\x1a\x1d.auth.ListDepartmentsResponse\x12Q\n" +
	"\x10UpdateDepartment\x12\x1d.auth.UpdateDepartmentRequest\x1a\x1e.auth.UpdateDepartmentResponse\x12Q\n" +
	"\x10DeleteDepartment\x12\x1d.auth.DeleteDepartmentRequest\x1a\x1e.auth.DeleteDepartmentResponse\x12H\n" +
	"\rGetDepartment\x12\x1a.auth.GetDepartmentRequest\x1a\x1b.auth.GetDepartmentResponse\x12W\n" +
	"\x12ReorderDepartments\x12\x1f.auth.ReorderDepartmentsRequest\x1a .auth.ReorderDepartmentsResponse\x12H\n" +
	"\rCreateProject\x12\x1a.auth.CreateProjectRequest\x1a\x1b.auth.CreateProjectResponse\x12Z\n" +
	"\x13BatchCreateProjects\x12 .auth.BatchCreateProjectsRequest\x1a!.auth.BatchCreateProjectsResponse\x12E\n" +
	"\fListProjects\x12\x19.auth.ListProjectsRequest\x1a\x1a.auth.ListProjectsResponse\x12H\n" +
	"\rUpdateProject\x12\x1a.auth.UpdateProjectRequest\x1a\x1b.auth.UpdateProjectResponse\x12H\n" +
	"\rDeleteProject\x12\x1a.auth.DeleteProjectRequest\x1a\x1b.auth.DeleteProjectResponse\x12?\n" +
	"\n" +
	"GetProject\x12\x17.auth.GetProjectRequest\x1a\x18.auth.GetProjectResponse\x12N\n" +
	"\x0fReorderProjects\x12\x1c.auth.ReorderProjectsRequest\x1a\x1d.auth.ReorderProjectsResponse\x12K\n" +
	"\x0eCreatePosition\x12\x1b.auth.CreatePositionRequest\x1a\x1c.auth.CreatePositionResponse\x12H\n" +
	"\rListPositions\x12\x1a.auth.ListPositionsRequest\x1a\x1b.auth.ListPositionsResponse\x12K\n" +
	"\x0eUpdatePosition\x12\x1b.auth.UpdatePositionRequest\x1a\x1c.auth.UpdatePositionResponse\x12K\n" +
	"\x0eDeletePosition\x12\x1b.auth.DeletePositionRequest\x1a\x1c.auth.DeletePositionResponse\x12Q\n" +
	"\x10ReorderPositions\x12\x1d.auth.ReorderPositionsRequest\x1a\x1e.auth.ReorderPositionsResponse\x12]\n" +
	"\x14BatchCreatePositions\x12!.auth.BatchCreatePositionsRequest\x1a\".auth.BatchCreatePositionsResponse\x12B\n" +
	"\vCheckAccess\x12\x18.auth.CheckAccessRequest\x1a\x19.auth.CheckAccessResponse\x12H\n" +
	"\rRequestAccess\x12\x1a.auth.RequestAccessRequest\x1a\x1b.auth.RequestAccessResponse\x12B\n" +
	"\vGrantAccess\x12\x18.auth.GrantAccessRequest\x1a\x19.auth.GrantAccessResponse\x12W\n" +
	"\x12ListAccessRequests\x12\x1f.auth.ListAccessRequestsRequest\x1a .auth.ListAccessRequestsResponse\x12c\n" +
	"\x16CreateDocumentMetadata\x12#.auth.CreateDocumentMetadataRequest\x1a$.auth.CreateDocumentMetadataResponse\x12i\n" +
	"\x18UpdateDocumentVisibility\x12%.auth.UpdateDocumentVisibilityRequest\x1a&.auth.UpdateDocumentVisibilityResponse\x12Z\n" +
	"\x13GetDocumentMetadata\x12 .auth.GetDocumentMetadataRequest\x1a!.auth.GetDocumentMetadataResponse\x12f\n" +
	"\x17ListVisibilityApprovals\x12$.auth.ListVisibilityApprovalsRequest\x1a%.auth.ListVisibilityApprovalsResponse\x12f\n" +
	"\x17ApproveVisibilityChange\x12$.auth.ApproveVisibilityChangeRequest\x1a%.auth.ApproveVisibilityChangeResponseB\x15Z\x13server/.protos/authb\x06proto3"

var (
	file_auth_auth_proto_rawDescOnce sync.Once
	file_auth_auth_proto_rawDescData []byte
)

func file_auth_auth_proto_rawDescGZIP() []byte {
	file_auth_auth_proto_rawDescOnce.Do(func() {
		file_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_auth_proto_rawDesc), len(file_auth_auth_proto_rawDesc)))
	})
	return file_auth_auth_proto_rawDescData
}

var file_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_auth_auth_proto_goTypes = []any{
	(*LoginRequest)(nil),                     // 0: auth.LoginRequest
	(*LoginResponse)(nil),                    // 1: auth.LoginResponse
	(*ValidateTokenRequest)(nil),             // 2: auth.ValidateTokenRequest
	(*ValidateTokenResponse)(nil),            // 3: auth.ValidateTokenResponse
	(*RefreshTokenRequest)(nil),              // 4: auth.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),             // 5: auth.RefreshTokenResponse
	(*CreateUserRequest)(nil),                // 6: auth.CreateUserRequest
	(*BatchCreateUsersRequest)(nil),          // 7: auth.BatchCreateUsersRequest
	(*GetUserRequest)(nil),                   // 8: auth.GetUserRequest
	(*ListUsersRequest)(nil),                 // 9: auth.ListUsersRequest
	(*UpdateUserRequest)(nil),                // 10: auth.UpdateUserRequest
	(*DeleteUserRequest)(nil),                // 11: auth.DeleteUserRequest
	(*CreateTenantRequest)(nil),              // 12: auth.CreateTenantRequest
	(*GetTenantRequest)(nil),                 // 13: auth.GetTenantRequest
	(*ListTenantsRequest)(nil),               // 14: auth.ListTenantsRequest
	(*CreateDepartmentRequest)(nil),          // 15: auth.CreateDepartmentRequest
	(*BatchCreateDepartmentsRequest)(nil),    // 16: auth.BatchCreateDepartmentsRequest
	(*ListDepartmentsRequest)(nil),           // 17: auth.ListDepartmentsRequest
	(*UpdateDepartmentRequest)(nil),          // 18: auth.UpdateDepartmentRequest
	(*DeleteDepartmentRequest)(nil),          // 19: auth.DeleteDepartmentRequest
	(*GetDepartmentRequest)(nil),             // 20: auth.GetDepartmentRequest
	(*ReorderDepartmentsRequest)(nil),        // 21: auth.ReorderDepartmentsRequest
	(*CreateProjectRequest)(nil),             // 22: auth.CreateProjectRequest
	(*BatchCreateProjectsRequest)(nil),       // 23: auth.BatchCreateProjectsRequest
	(*ListProjectsRequest)(nil),              // 24: auth.ListProjectsRequest
	(*UpdateProjectRequest)(nil),             // 25: auth.UpdateProjectRequest
	(*DeleteProjectRequest)(nil),             // 26: auth.DeleteProjectRequest
	(*GetProjectRequest)(nil),                // 27: auth.GetProjectRequest
	(*ReorderProjectsRequest)(nil),           // 28: auth.ReorderProjectsRequest
	(*CreatePositionRequest)(nil),            // 29: auth.CreatePositionRequest
	(*ListPositionsRequest)(nil),             // 30: auth.ListPositionsRequest
	(*UpdatePositionRequest)(nil),            // 31: auth.UpdatePositionRequest
	(*DeletePositionRequest)(nil),            // 32: auth.DeletePositionRequest
	(*ReorderPositionsRequest)(nil),          // 33: auth.ReorderPositionsRequest
	(*BatchCreatePositionsRequest)(nil),      // 34: auth.BatchCreatePositionsRequest
	(*CheckAccessRequest)(nil),               // 35: auth.CheckAccessRequest
	(*RequestAccessRequest)(nil),             // 36: auth.RequestAccessRequest
	(*GrantAccessRequest)(nil),               // 37: auth.GrantAccessRequest
	(*ListAccessRequestsRequest)(nil),        // 38: auth.ListAccessRequestsRequest
	(*CreateDocumentMetadataRequest)(nil),    // 39: auth.CreateDocumentMetadataRequest
	(*UpdateDocumentVisibilityRequest)(nil),  // 40: auth.UpdateDocumentVisibilityRequest
	(*GetDocumentMetadataRequest)(nil),       // 41: auth.GetDocumentMetadataRequest
	(*ListVisibilityApprovalsRequest)(nil),   // 42: auth.ListVisibilityApprovalsRequest
	(*ApproveVisibilityChangeRequest)(nil),   // 43: auth.ApproveVisibilityChangeRequest
	(*CreateUserResponse)(nil),               // 44: auth.CreateUserResponse
	(*BatchCreateUsersResponse)(nil),         // 45: auth.BatchCreateUsersResponse
	(*GetUserResponse)(nil),                  // 46: auth.GetUserResponse
	(*ListUsersResponse)(nil),                // 47: auth.ListUsersResponse
	(*UpdateUserResponse)(nil),               // 48: auth.UpdateUserResponse
	(*DeleteUserResponse)(nil),               // 49: auth.DeleteUserResponse
	(*CreateTenantResponse)(nil),             // 50: auth.CreateTenantResponse
	(*GetTenantResponse)(nil),                // 51: auth.GetTenantResponse
	(*ListTenantsResponse)(nil),              // 52: auth.ListTenantsResponse
	(*CreateDepartmentResponse)(nil),         // 53: auth.CreateDepartmentResponse
	(*BatchCreateDepartmentsResponse)(nil),   // 54: auth.BatchCreateDepartmentsResponse
	(*ListDepartmentsResponse)(nil),          // 55: auth.ListDepartmentsResponse
	(*UpdateDepartmentResponse)(nil),         // 56: auth.UpdateDepartmentResponse
	(*DeleteDepartmentResponse)(nil),         // 57: auth.DeleteDepartmentResponse
	(*GetDepartmentResponse)(nil),            // 58: auth.GetDepartmentResponse
	(*ReorderDepartmentsResponse)(nil),       // 59: auth.ReorderDepartmentsResponse
	(*CreateProjectResponse)(nil),            // 60: auth.CreateProjectResponse
	(*BatchCreateProjectsResponse)(nil),      // 61: auth.BatchCreateProjectsResponse
	(*ListProjectsResponse)(nil),             // 62: auth.ListProjectsResponse
	(*UpdateProjectResponse)(nil),            // 63: auth.UpdateProjectResponse
	(*DeleteProjectResponse)(nil),            // 64: auth.DeleteProjectResponse
	(*GetProjectResponse)(nil),               // 65: auth.GetProjectResponse
	(*ReorderProjectsResponse)(nil),          // 66: auth.ReorderProjectsResponse
	(*CreatePositionResponse)(nil),           // 67: auth.CreatePositionResponse
	(*ListPositionsResponse)(nil),            // 68: auth.ListPositionsResponse
	(*UpdatePositionResponse)(nil),           // 69: auth.UpdatePositionResponse
	(*DeletePositionResponse)(nil),           // 70: auth.DeletePositionResponse
	(*ReorderPositionsResponse)(nil),         // 71: auth.ReorderPositionsResponse
	(*BatchCreatePositionsResponse)(nil),     // 72: auth.BatchCreatePositionsResponse
	(*CheckAccessResponse)(nil),              // 73: auth.CheckAccessResponse
	(*RequestAccessResponse)(nil),            // 74: auth.RequestAccessResponse
	(*GrantAccessResponse)(nil),              // 75: auth.GrantAccessResponse
	(*ListAccessRequestsResponse)(nil),       // 76: auth.ListAccessRequestsResponse
	(*CreateDocumentMetadataResponse)(nil),   // 77: auth.CreateDocumentMetadataResponse
	(*UpdateDocumentVisibilityResponse)(nil), // 78: auth.UpdateDocumentVisibilityResponse
	(*GetDocumentMetadataResponse)(nil),      // 79: auth.GetDocumentMetadataResponse
	(*ListVisibilityApprovalsResponse)(nil),  // 80: auth.ListVisibilityApprovalsResponse
	(*ApproveVisibilityChangeResponse)(nil),  // 81: auth.ApproveVisibilityChangeResponse
}
var file_auth_auth_proto_depIdxs = []int32{
	0,  // 0: auth.AuthService.Login:input_type -> auth.LoginRequest
	2,  // 1: auth.AuthService.ValidateToken:input_type -> auth.ValidateTokenRequest
	4,  // 2: auth.AuthService.RefreshToken:input_type -> auth.RefreshTokenRequest
	6,  // 3: auth.AuthService.CreateUser:input_type -> auth.CreateUserRequest
	7,  // 4: auth.AuthService.BatchCreateUsers:input_type -> auth.BatchCreateUsersRequest
	8,  // 5: auth.AuthService.GetUser:input_type -> auth.GetUserRequest
	9,  // 6: auth.AuthService.ListUsers:input_type -> auth.ListUsersRequest
	10, // 7: auth.AuthService.UpdateUser:input_type -> auth.UpdateUserRequest
	11, // 8: auth.AuthService.DeleteUser:input_type -> auth.DeleteUserRequest
	12, // 9: auth.AuthService.CreateTenant:input_type -> auth.CreateTenantRequest
	13, // 10: auth.AuthService.GetTenant:input_type -> auth.GetTenantRequest
	14, // 11: auth.AuthService.ListTenants:input_type -> auth.ListTenantsRequest
	15, // 12: auth.AuthService.CreateDepartment:input_type -> auth.CreateDepartmentRequest
	16, // 13: auth.AuthService.BatchCreateDepartments:input_type -> auth.BatchCreateDepartmentsRequest
	17, // 14: auth.AuthService.ListDepartments:input_type -> auth.ListDepartmentsRequest
	18, // 15: auth.AuthService.UpdateDepartment:input_type -> auth.UpdateDepartmentRequest
	19, // 16: auth.AuthService.DeleteDepartment:input_type -> auth.DeleteDepartmentRequest
	20, // 17: auth.AuthService.GetDepartment:input_type -> auth.GetDepartmentRequest
	21, // 18: auth.AuthService.ReorderDepartments:input_type -> auth.ReorderDepartmentsRequest
	22, // 19: auth.AuthService.CreateProject:input_type -> auth.CreateProjectRequest
	23, // 20: auth.AuthService.BatchCreateProjects:input_type -> auth.BatchCreateProjectsRequest
	24, // 21: auth.AuthService.ListProjects:input_type -> auth.ListProjectsRequest
	25, // 22: auth.AuthService.UpdateProject:input_type -> auth.UpdateProjectRequest
	26, // 23: auth.AuthService.DeleteProject:input_type -> auth.DeleteProjectRequest
	27, // 24: auth.AuthService.GetProject:input_type -> auth.GetProjectRequest
	28, // 25: auth.AuthService.ReorderProjects:input_type -> auth.ReorderProjectsRequest
	29, // 26: auth.AuthService.CreatePosition:input_type -> auth.CreatePositionRequest
	30, // 27: auth.AuthService.ListPositions:input_type -> auth.ListPositionsRequest
	31, // 28: auth.AuthService.UpdatePosition:input_type -> auth.UpdatePositionRequest
	32, // 29: auth.AuthService.DeletePosition:input_type -> auth.DeletePositionRequest
	33, // 30: auth.AuthService.ReorderPositions:input_type -> auth.ReorderPositionsRequest
	34, // 31: auth.AuthService.BatchCreatePositions:input_type -> auth.BatchCreatePositionsRequest
	35, // 32: auth.AuthService.CheckAccess:input_type -> auth.CheckAccessRequest
	36, // 33: auth.AuthService.RequestAccess:input_type -> auth.RequestAccessRequest
	37, // 34: auth.AuthService.GrantAccess:input_type -> auth.GrantAccessRequest
	38, // 35: auth.AuthService.ListAccessRequests:input_type -> auth.ListAccessRequestsRequest
	39, // 36: auth.AuthService.CreateDocumentMetadata:input_type -> auth.CreateDocumentMetadataRequest
	40, // 37: auth.AuthService.UpdateDocumentVisibility:input_type -> auth.UpdateDocumentVisibilityRequest
	41, // 38: auth.AuthService.GetDocumentMetadata:input_type -> auth.GetDocumentMetadataRequest
	42, // 39: auth.AuthService.ListVisibilityApprovals:input_type -> auth.ListVisibilityApprovalsRequest
	43, // 40: auth.AuthService.ApproveVisibilityChange:input_type -> auth.ApproveVisibilityChangeRequest
	1,  // 41: auth.AuthService.Login:output_type -> auth.LoginResponse
	3,  // 42: auth.AuthService.ValidateToken:output_type -> auth.ValidateTokenResponse
	5,  // 43: auth.AuthService.RefreshToken:output_type -> auth.RefreshTokenResponse
	44, // 44: auth.AuthService.CreateUser:output_type -> auth.CreateUserResponse
	45, // 45: auth.AuthService.BatchCreateUsers:output_type -> auth.BatchCreateUsersResponse
	46, // 46: auth.AuthService.GetUser:output_type -> auth.GetUserResponse
	47, // 47: auth.AuthService.ListUsers:output_type -> auth.ListUsersResponse
	48, // 48: auth.AuthService.UpdateUser:output_type -> auth.UpdateUserResponse
	49, // 49: auth.AuthService.DeleteUser:output_type -> auth.DeleteUserResponse
	50, // 50: auth.AuthService.CreateTenant:output_type -> auth.CreateTenantResponse
	51, // 51: auth.AuthService.GetTenant:output_type -> auth.GetTenantResponse
	52, // 52: auth.AuthService.ListTenants:output_type -> auth.ListTenantsResponse
	53, // 53: auth.AuthService.CreateDepartment:output_type -> auth.CreateDepartmentResponse
	54, // 54: auth.AuthService.BatchCreateDepartments:output_type -> auth.BatchCreateDepartmentsResponse
	55, // 55: auth.AuthService.ListDepartments:output_type -> auth.ListDepartmentsResponse
	56, // 56: auth.AuthService.UpdateDepartment:output_type -> auth.UpdateDepartmentResponse
	57, // 57: auth.AuthService.DeleteDepartment:output_type -> auth.DeleteDepartmentResponse
	58, // 58: auth.AuthService.GetDepartment:output_type -> auth.GetDepartmentResponse
	59, // 59: auth.AuthService.ReorderDepartments:output_type -> auth.ReorderDepartmentsResponse
	60, // 60: auth.AuthService.CreateProject:output_type -> auth.CreateProjectResponse
	61, // 61: auth.AuthService.BatchCreateProjects:output_type -> auth.BatchCreateProjectsResponse
	62, // 62: auth.AuthService.ListProjects:output_type -> auth.ListProjectsResponse
	63, // 63: auth.AuthService.UpdateProject:output_type -> auth.UpdateProjectResponse
	64, // 64: auth.AuthService.DeleteProject:output_type -> auth.DeleteProjectResponse
	65, // 65: auth.AuthService.GetProject:output_type -> auth.GetProjectResponse
	66, // 66: auth.AuthService.ReorderProjects:output_type -> auth.ReorderProjectsResponse
	67, // 67: auth.AuthService.CreatePosition:output_type -> auth.CreatePositionResponse
	68, // 68: auth.AuthService.ListPositions:output_type -> auth.ListPositionsResponse
	69, // 69: auth.AuthService.UpdatePosition:output_type -> auth.UpdatePositionResponse
	70, // 70: auth.AuthService.DeletePosition:output_type -> auth.DeletePositionResponse
	71, // 71: auth.AuthService.ReorderPositions:output_type -> auth.ReorderPositionsResponse
	72, // 72: auth.AuthService.BatchCreatePositions:output_type -> auth.BatchCreatePositionsResponse
	73, // 73: auth.AuthService.CheckAccess:output_type -> auth.CheckAccessResponse
	74, // 74: auth.AuthService.RequestAccess:output_type -> auth.RequestAccessResponse
	75, // 75: auth.AuthService.GrantAccess:output_type -> auth.GrantAccessResponse
	76, // 76: auth.AuthService.ListAccessRequests:output_type -> auth.ListAccessRequestsResponse
	77, // 77: auth.AuthService.CreateDocumentMetadata:output_type -> auth.CreateDocumentMetadataResponse
	78, // 78: auth.AuthService.UpdateDocumentVisibility:output_type -> auth.UpdateDocumentVisibilityResponse
	79, // 79: auth.AuthService.GetDocumentMetadata:output_type -> auth.GetDocumentMetadataResponse
	80, // 80: auth.AuthService.ListVisibilityApprovals:output_type -> auth.ListVisibilityApprovalsResponse
	81, // 81: auth.AuthService.ApproveVisibilityChange:output_type -> auth.ApproveVisibilityChangeResponse
	41, // [41:82] is the sub-list for method output_type
	0,  // [0:41] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_auth_auth_proto_init() }
func file_auth_auth_proto_init() {
	if File_auth_auth_proto != nil {
		return
	}
	file_auth_user_proto_init()
	file_auth_tenant_proto_init()
	file_auth_acl_proto_init()
	file_auth_department_proto_init()
	file_auth_project_proto_init()
	file_auth_document_proto_init()
	file_auth_position_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_auth_proto_rawDesc), len(file_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_auth_proto_goTypes,
		DependencyIndexes: file_auth_auth_proto_depIdxs,
		MessageInfos:      file_auth_auth_proto_msgTypes,
	}.Build()
	File_auth_auth_proto = out.File
	file_auth_auth_proto_goTypes = nil
	file_auth_auth_proto_depIdxs = nil
}
