// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: auth/auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 로그인 요청
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // Added for tenant isolation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 로그인 응답
type LoginResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AccessToken         string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken        string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	TenantId            string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ExpiresIn           int64                  `protobuf:"varint,4,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	Role                string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	ForceChangePassword bool                   `protobuf:"varint,6,opt,name=force_change_password,json=forceChangePassword,proto3" json:"force_change_password,omitempty"`
	// User info for offline caching
	UserId     string `protobuf:"bytes,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username   string `protobuf:"bytes,8,opt,name=username,proto3" json:"username,omitempty"`
	PositionId string `protobuf:"bytes,9,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	// department_id removed
	PhoneNumbers []string `protobuf:"bytes,11,rep,name=phone_numbers,json=phoneNumbers,proto3" json:"phone_numbers,omitempty"`
	Contact      string   `protobuf:"bytes,12,opt,name=contact,proto3" json:"contact,omitempty"`
	CreatedAt    string   `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt    string   `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// department_name removed
	PositionName   string      `protobuf:"bytes,16,opt,name=position_name,json=positionName,proto3" json:"position_name,omitempty"`
	JoinedProjects []*Project  `protobuf:"bytes,17,rep,name=joined_projects,json=joinedProjects,proto3" json:"joined_projects,omitempty"`
	Department     *Department `protobuf:"bytes,18,opt,name=department,proto3" json:"department,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_auth_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *LoginResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *LoginResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *LoginResponse) GetForceChangePassword() bool {
	if x != nil {
		return x.ForceChangePassword
	}
	return false
}

func (x *LoginResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoginResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginResponse) GetPositionId() string {
	if x != nil {
		return x.PositionId
	}
	return ""
}

func (x *LoginResponse) GetPhoneNumbers() []string {
	if x != nil {
		return x.PhoneNumbers
	}
	return nil
}

func (x *LoginResponse) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

func (x *LoginResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *LoginResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *LoginResponse) GetPositionName() string {
	if x != nil {
		return x.PositionName
	}
	return ""
}

func (x *LoginResponse) GetJoinedProjects() []*Project {
	if x != nil {
		return x.JoinedProjects
	}
	return nil
}

func (x *LoginResponse) GetDepartment() *Department {
	if x != nil {
		return x.Department
	}
	return nil
}

type ResetAndSendPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetAndSendPasswordRequest) Reset() {
	*x = ResetAndSendPasswordRequest{}
	mi := &file_auth_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetAndSendPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetAndSendPasswordRequest) ProtoMessage() {}

func (x *ResetAndSendPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetAndSendPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetAndSendPasswordRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{3}
}

func (x *ResetAndSendPasswordRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ResetAndSendPasswordRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ResetAndSendPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetAndSendPasswordResponse) Reset() {
	*x = ResetAndSendPasswordResponse{}
	mi := &file_auth_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetAndSendPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetAndSendPasswordResponse) ProtoMessage() {}

func (x *ResetAndSendPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetAndSendPasswordResponse.ProtoReflect.Descriptor instead.
func (*ResetAndSendPasswordResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{4}
}

func (x *ResetAndSendPasswordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 토큰 검증 요청
type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_auth_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

// 토큰 검증 응답
type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserSalt      string                 `protobuf:"bytes,3,opt,name=user_salt,json=userSalt,proto3" json:"user_salt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_auth_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateTokenResponse) GetUserSalt() string {
	if x != nil {
		return x.UserSalt
	}
	return ""
}

// 리프레시 토큰 요청
type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_auth_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{7}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// 리프레시 토큰 응답
type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_auth_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{8}
}

func (x *RefreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_auth_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{9}
}

func (x *LogoutRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LogoutRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_auth_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{10}
}

func (x *LogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Tenant lookup by email (for client apps without subdomain)
type LookupTenantByEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupTenantByEmailRequest) Reset() {
	*x = LookupTenantByEmailRequest{}
	mi := &file_auth_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupTenantByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupTenantByEmailRequest) ProtoMessage() {}

func (x *LookupTenantByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupTenantByEmailRequest.ProtoReflect.Descriptor instead.
func (*LookupTenantByEmailRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{11}
}

func (x *LookupTenantByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type TenantInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // Display name for UI
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantInfo) Reset() {
	*x = TenantInfo{}
	mi := &file_auth_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantInfo) ProtoMessage() {}

func (x *TenantInfo) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantInfo.ProtoReflect.Descriptor instead.
func (*TenantInfo) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{12}
}

func (x *TenantInfo) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TenantInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LookupTenantByEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenants       []*TenantInfo          `protobuf:"bytes,1,rep,name=tenants,proto3" json:"tenants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupTenantByEmailResponse) Reset() {
	*x = LookupTenantByEmailResponse{}
	mi := &file_auth_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupTenantByEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupTenantByEmailResponse) ProtoMessage() {}

func (x *LookupTenantByEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupTenantByEmailResponse.ProtoReflect.Descriptor instead.
func (*LookupTenantByEmailResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{13}
}

func (x *LookupTenantByEmailResponse) GetTenants() []*TenantInfo {
	if x != nil {
		return x.Tenants
	}
	return nil
}

var File_auth_auth_proto protoreflect.FileDescriptor

const file_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x0fauth/auth.proto\x12\x04auth\x1a\x0fauth/user.proto\x1a\x11auth/tenant.proto\x1a\x0eauth/acl.proto\x1a\x15auth/department.proto\x1a\x12auth/project.proto\x1a\x13auth/document.proto\x1a\x13auth/position.proto\"]\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\"C\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xbd\x04\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x04 \x01(\x03R\texpiresIn\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x122\n" +
	"\x15force_change_password\x18\x06 \x01(\bR\x13forceChangePassword\x12\x17\n" +
	"\auser_id\x18\a \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\b \x01(\tR\busername\x12\x1f\n" +
	"\vposition_id\x18\t \x01(\tR\n" +
	"positionId\x12#\n" +
	"\rphone_numbers\x18\v \x03(\tR\fphoneNumbers\x12\x18\n" +
	"\acontact\x18\f \x01(\tR\acontact\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\tR\tupdatedAt\x12#\n" +
	"\rposition_name\x18\x10 \x01(\tR\fpositionName\x126\n" +
	"\x0fjoined_projects\x18\x11 \x03(\v2\r.auth.ProjectR\x0ejoinedProjects\x120\n" +
	"\n" +
	"department\x18\x12 \x01(\v2\x10.auth.DepartmentR\n" +
	"department\"S\n" +
	"\x1bResetAndSendPasswordRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"8\n" +
	"\x1cResetAndSendPasswordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"9\n" +
	"\x14ValidateTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"c\n" +
	"\x15ValidateTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_salt\x18\x03 \x01(\tR\buserSalt\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"^\n" +
	"\x14RefreshTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"W\n" +
	"\rLogoutRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"*\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"2\n" +
	"\x1aLookupTenantByEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"=\n" +
	"\n" +
	"TenantInfo\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"I\n" +
	"\x1bLookupTenantByEmailResponse\x12*\n" +
	"\atenants\x18\x01 \x03(\v2\x10.auth.TenantInfoR\atenants2\xa8\x1c\n" +
	"\vAuthService\x120\n" +
	"\x05Login\x12\x12.auth.LoginRequest\x1a\x13.auth.LoginResponse\x12Z\n" +
	"\x13LookupTenantByEmail\x12 .auth.LookupTenantByEmailRequest\x1a!.auth.LookupTenantByEmailResponse\x12H\n" +
	"\rValidateToken\x12\x1a.auth.ValidateTokenRequest\x1a\x1b.auth.ValidateTokenResponse\x12E\n" +
	"\fRefreshToken\x12\x19.auth.RefreshTokenRequest\x1a\x1a.auth.RefreshTokenResponse\x12?\n" +
	"\n" +
	"CreateUser\x12\x17.auth.CreateUserRequest\x1a\x18.auth.CreateUserResponse\x12Q\n" +
	"\x10BatchCreateUsers\x12\x1d.auth.BatchCreateUsersRequest\x1a\x1e.auth.BatchCreateUsersResponse\x126\n" +
	"\aGetUser\x12\x14.auth.GetUserRequest\x1a\x15.auth.GetUserResponse\x12<\n" +
	"\tListUsers\x12\x16.auth.ListUsersRequest\x1a\x17.auth.ListUsersResponse\x12?\n" +
	"\n" +
	"UpdateUser\x12\x17.auth.UpdateUserRequest\x1a\x18.auth.UpdateUserResponse\x12?\n" +
	"\n" +
	"DeleteUser\x12\x17.auth.DeleteUserRequest\x1a\x18.auth.DeleteUserResponse\x12E\n" +
	"\fCreateTenant\x12\x19.auth.CreateTenantRequest\x1a\x1a.auth.CreateTenantResponse\x12<\n" +
	"\tGetTenant\x12\x16.auth.GetTenantRequest\x1a\x17.auth.GetTenantResponse\x12B\n" +
	"\vListTenants\x12\x18.auth.ListTenantsRequest\x1a\x19.auth.ListTenantsResponse\x12Q\n" +
	"\x10CreateDepartment\x12\x1d.auth.CreateDepartmentRequest\x1a\x1e.auth.CreateDepartmentResponse\x12c\n" +
	"\x16BatchCreateDepartments\x12#.auth.BatchCreateDepartmentsRequest\x1a$.auth.BatchCreateDepartmentsResponse\x12N\n" +
	"\x0fListDepartments\x12\x1c.auth.ListDepartmentsRequest\x1a\x1d.auth.ListDepartmentsResponse\x12Q\n" +
	"\x10UpdateDepartment\x12\x1d.auth.UpdateDepartmentRequest\x1a\x1e.auth.UpdateDepartmentResponse\x12Q\n" +
	"\x10DeleteDepartment\x12\x1d.auth.DeleteDepartmentRequest\x1a\x1e.auth.DeleteDepartmentResponse\x12H\n" +
	"\rGetDepartment\x12\x1a.auth.GetDepartmentRequest\x1a\x1b.auth.GetDepartmentResponse\x12W\n" +
	"\x12ReorderDepartments\x12\x1f.auth.ReorderDepartmentsRequest\x1a .auth.ReorderDepartmentsResponse\x12H\n" +
	"\rCreateProject\x12\x1a.auth.CreateProjectRequest\x1a\x1b.auth.CreateProjectResponse\x12Z\n" +
	"\x13BatchCreateProjects\x12 .auth.BatchCreateProjectsRequest\x1a!.auth.BatchCreateProjectsResponse\x12E\n" +
	"\fListProjects\x12\x19.auth.ListProjectsRequest\x1a\x1a.auth.ListProjectsResponse\x12H\n" +
	"\rUpdateProject\x12\x1a.auth.UpdateProjectRequest\x1a\x1b.auth.UpdateProjectResponse\x12H\n" +
	"\rDeleteProject\x12\x1a.auth.DeleteProjectRequest\x1a\x1b.auth.DeleteProjectResponse\x12?\n" +
	"\n" +
	"GetProject\x12\x17.auth.GetProjectRequest\x1a\x18.auth.GetProjectResponse\x12N\n" +
	"\x0fReorderProjects\x12\x1c.auth.ReorderProjectsRequest\x1a\x1d.auth.ReorderProjectsResponse\x12K\n" +
	"\x0eCreatePosition\x12\x1b.auth.CreatePositionRequest\x1a\x1c.auth.CreatePositionResponse\x12H\n" +
	"\rListPositions\x12\x1a.auth.ListPositionsRequest\x1a\x1b.auth.ListPositionsResponse\x12K\n" +
	"\x0eUpdatePosition\x12\x1b.auth.UpdatePositionRequest\x1a\x1c.auth.UpdatePositionResponse\x12K\n" +
	"\x0eDeletePosition\x12\x1b.auth.DeletePositionRequest\x1a\x1c.auth.DeletePositionResponse\x12Q\n" +
	"\x10ReorderPositions\x12\x1d.auth.ReorderPositionsRequest\x1a\x1e.auth.ReorderPositionsResponse\x12]\n" +
	"\x14BatchCreatePositions\x12!.auth.BatchCreatePositionsRequest\x1a\".auth.BatchCreatePositionsResponse\x12B\n" +
	"\vCheckAccess\x12\x18.auth.CheckAccessRequest\x1a\x19.auth.CheckAccessResponse\x12H\n" +
	"\rRequestAccess\x12\x1a.auth.RequestAccessRequest\x1a\x1b.auth.RequestAccessResponse\x12B\n" +
	"\vGrantAccess\x12\x18.auth.GrantAccessRequest\x1a\x19.auth.GrantAccessResponse\x12W\n" +
	"\x12ListAccessRequests\x12\x1f.auth.ListAccessRequestsRequest\x1a .auth.ListAccessRequestsResponse\x12c\n" +
	"\x16CreateDocumentMetadata\x12#.auth.CreateDocumentMetadataRequest\x1a$.auth.CreateDocumentMetadataResponse\x12i\n" +
	"\x18UpdateDocumentVisibility\x12%.auth.UpdateDocumentVisibilityRequest\x1a&.auth.UpdateDocumentVisibilityResponse\x12Z\n" +
	"\x13GetDocumentMetadata\x12 .auth.GetDocumentMetadataRequest\x1a!.auth.GetDocumentMetadataResponse\x12f\n" +
	"\x17ListVisibilityApprovals\x12$.auth.ListVisibilityApprovalsRequest\x1a%.auth.ListVisibilityApprovalsResponse\x12f\n" +
	"\x17ApproveVisibilityChange\x12$.auth.ApproveVisibilityChangeRequest\x1a%.auth.ApproveVisibilityChangeResponse\x12]\n" +
	"\x14ResetAndSendPassword\x12!.auth.ResetAndSendPasswordRequest\x1a\".auth.ResetAndSendPasswordResponse\x12W\n" +
	"\x12BatchResetPassword\x12\x1f.auth.BatchResetPasswordRequest\x1a .auth.BatchResetPasswordResponse\x12K\n" +
	"\x0eChangePassword\x12\x1b.auth.ChangePasswordRequest\x1a\x1c.auth.ChangePasswordResponse\x123\n" +
	"\x06Logout\x12\x13.auth.LogoutRequest\x1a\x14.auth.LogoutResponseB\x15Z\x13server/.protos/authb\x06proto3"

var (
	file_auth_auth_proto_rawDescOnce sync.Once
	file_auth_auth_proto_rawDescData []byte
)

func file_auth_auth_proto_rawDescGZIP() []byte {
	file_auth_auth_proto_rawDescOnce.Do(func() {
		file_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_auth_proto_rawDesc), len(file_auth_auth_proto_rawDesc)))
	})
	return file_auth_auth_proto_rawDescData
}

var file_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_auth_auth_proto_goTypes = []any{
	(*LoginRequest)(nil),                     // 0: auth.LoginRequest
	(*RegisterRequest)(nil),                  // 1: auth.RegisterRequest
	(*LoginResponse)(nil),                    // 2: auth.LoginResponse
	(*ResetAndSendPasswordRequest)(nil),      // 3: auth.ResetAndSendPasswordRequest
	(*ResetAndSendPasswordResponse)(nil),     // 4: auth.ResetAndSendPasswordResponse
	(*ValidateTokenRequest)(nil),             // 5: auth.ValidateTokenRequest
	(*ValidateTokenResponse)(nil),            // 6: auth.ValidateTokenResponse
	(*RefreshTokenRequest)(nil),              // 7: auth.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),             // 8: auth.RefreshTokenResponse
	(*LogoutRequest)(nil),                    // 9: auth.LogoutRequest
	(*LogoutResponse)(nil),                   // 10: auth.LogoutResponse
	(*LookupTenantByEmailRequest)(nil),       // 11: auth.LookupTenantByEmailRequest
	(*TenantInfo)(nil),                       // 12: auth.TenantInfo
	(*LookupTenantByEmailResponse)(nil),      // 13: auth.LookupTenantByEmailResponse
	(*Project)(nil),                          // 14: auth.Project
	(*Department)(nil),                       // 15: auth.Department
	(*CreateUserRequest)(nil),                // 16: auth.CreateUserRequest
	(*BatchCreateUsersRequest)(nil),          // 17: auth.BatchCreateUsersRequest
	(*GetUserRequest)(nil),                   // 18: auth.GetUserRequest
	(*ListUsersRequest)(nil),                 // 19: auth.ListUsersRequest
	(*UpdateUserRequest)(nil),                // 20: auth.UpdateUserRequest
	(*DeleteUserRequest)(nil),                // 21: auth.DeleteUserRequest
	(*CreateTenantRequest)(nil),              // 22: auth.CreateTenantRequest
	(*GetTenantRequest)(nil),                 // 23: auth.GetTenantRequest
	(*ListTenantsRequest)(nil),               // 24: auth.ListTenantsRequest
	(*CreateDepartmentRequest)(nil),          // 25: auth.CreateDepartmentRequest
	(*BatchCreateDepartmentsRequest)(nil),    // 26: auth.BatchCreateDepartmentsRequest
	(*ListDepartmentsRequest)(nil),           // 27: auth.ListDepartmentsRequest
	(*UpdateDepartmentRequest)(nil),          // 28: auth.UpdateDepartmentRequest
	(*DeleteDepartmentRequest)(nil),          // 29: auth.DeleteDepartmentRequest
	(*GetDepartmentRequest)(nil),             // 30: auth.GetDepartmentRequest
	(*ReorderDepartmentsRequest)(nil),        // 31: auth.ReorderDepartmentsRequest
	(*CreateProjectRequest)(nil),             // 32: auth.CreateProjectRequest
	(*BatchCreateProjectsRequest)(nil),       // 33: auth.BatchCreateProjectsRequest
	(*ListProjectsRequest)(nil),              // 34: auth.ListProjectsRequest
	(*UpdateProjectRequest)(nil),             // 35: auth.UpdateProjectRequest
	(*DeleteProjectRequest)(nil),             // 36: auth.DeleteProjectRequest
	(*GetProjectRequest)(nil),                // 37: auth.GetProjectRequest
	(*ReorderProjectsRequest)(nil),           // 38: auth.ReorderProjectsRequest
	(*CreatePositionRequest)(nil),            // 39: auth.CreatePositionRequest
	(*ListPositionsRequest)(nil),             // 40: auth.ListPositionsRequest
	(*UpdatePositionRequest)(nil),            // 41: auth.UpdatePositionRequest
	(*DeletePositionRequest)(nil),            // 42: auth.DeletePositionRequest
	(*ReorderPositionsRequest)(nil),          // 43: auth.ReorderPositionsRequest
	(*BatchCreatePositionsRequest)(nil),      // 44: auth.BatchCreatePositionsRequest
	(*CheckAccessRequest)(nil),               // 45: auth.CheckAccessRequest
	(*RequestAccessRequest)(nil),             // 46: auth.RequestAccessRequest
	(*GrantAccessRequest)(nil),               // 47: auth.GrantAccessRequest
	(*ListAccessRequestsRequest)(nil),        // 48: auth.ListAccessRequestsRequest
	(*CreateDocumentMetadataRequest)(nil),    // 49: auth.CreateDocumentMetadataRequest
	(*UpdateDocumentVisibilityRequest)(nil),  // 50: auth.UpdateDocumentVisibilityRequest
	(*GetDocumentMetadataRequest)(nil),       // 51: auth.GetDocumentMetadataRequest
	(*ListVisibilityApprovalsRequest)(nil),   // 52: auth.ListVisibilityApprovalsRequest
	(*ApproveVisibilityChangeRequest)(nil),   // 53: auth.ApproveVisibilityChangeRequest
	(*BatchResetPasswordRequest)(nil),        // 54: auth.BatchResetPasswordRequest
	(*ChangePasswordRequest)(nil),            // 55: auth.ChangePasswordRequest
	(*CreateUserResponse)(nil),               // 56: auth.CreateUserResponse
	(*BatchCreateUsersResponse)(nil),         // 57: auth.BatchCreateUsersResponse
	(*GetUserResponse)(nil),                  // 58: auth.GetUserResponse
	(*ListUsersResponse)(nil),                // 59: auth.ListUsersResponse
	(*UpdateUserResponse)(nil),               // 60: auth.UpdateUserResponse
	(*DeleteUserResponse)(nil),               // 61: auth.DeleteUserResponse
	(*CreateTenantResponse)(nil),             // 62: auth.CreateTenantResponse
	(*GetTenantResponse)(nil),                // 63: auth.GetTenantResponse
	(*ListTenantsResponse)(nil),              // 64: auth.ListTenantsResponse
	(*CreateDepartmentResponse)(nil),         // 65: auth.CreateDepartmentResponse
	(*BatchCreateDepartmentsResponse)(nil),   // 66: auth.BatchCreateDepartmentsResponse
	(*ListDepartmentsResponse)(nil),          // 67: auth.ListDepartmentsResponse
	(*UpdateDepartmentResponse)(nil),         // 68: auth.UpdateDepartmentResponse
	(*DeleteDepartmentResponse)(nil),         // 69: auth.DeleteDepartmentResponse
	(*GetDepartmentResponse)(nil),            // 70: auth.GetDepartmentResponse
	(*ReorderDepartmentsResponse)(nil),       // 71: auth.ReorderDepartmentsResponse
	(*CreateProjectResponse)(nil),            // 72: auth.CreateProjectResponse
	(*BatchCreateProjectsResponse)(nil),      // 73: auth.BatchCreateProjectsResponse
	(*ListProjectsResponse)(nil),             // 74: auth.ListProjectsResponse
	(*UpdateProjectResponse)(nil),            // 75: auth.UpdateProjectResponse
	(*DeleteProjectResponse)(nil),            // 76: auth.DeleteProjectResponse
	(*GetProjectResponse)(nil),               // 77: auth.GetProjectResponse
	(*ReorderProjectsResponse)(nil),          // 78: auth.ReorderProjectsResponse
	(*CreatePositionResponse)(nil),           // 79: auth.CreatePositionResponse
	(*ListPositionsResponse)(nil),            // 80: auth.ListPositionsResponse
	(*UpdatePositionResponse)(nil),           // 81: auth.UpdatePositionResponse
	(*DeletePositionResponse)(nil),           // 82: auth.DeletePositionResponse
	(*ReorderPositionsResponse)(nil),         // 83: auth.ReorderPositionsResponse
	(*BatchCreatePositionsResponse)(nil),     // 84: auth.BatchCreatePositionsResponse
	(*CheckAccessResponse)(nil),              // 85: auth.CheckAccessResponse
	(*RequestAccessResponse)(nil),            // 86: auth.RequestAccessResponse
	(*GrantAccessResponse)(nil),              // 87: auth.GrantAccessResponse
	(*ListAccessRequestsResponse)(nil),       // 88: auth.ListAccessRequestsResponse
	(*CreateDocumentMetadataResponse)(nil),   // 89: auth.CreateDocumentMetadataResponse
	(*UpdateDocumentVisibilityResponse)(nil), // 90: auth.UpdateDocumentVisibilityResponse
	(*GetDocumentMetadataResponse)(nil),      // 91: auth.GetDocumentMetadataResponse
	(*ListVisibilityApprovalsResponse)(nil),  // 92: auth.ListVisibilityApprovalsResponse
	(*ApproveVisibilityChangeResponse)(nil),  // 93: auth.ApproveVisibilityChangeResponse
	(*BatchResetPasswordResponse)(nil),       // 94: auth.BatchResetPasswordResponse
	(*ChangePasswordResponse)(nil),           // 95: auth.ChangePasswordResponse
}
var file_auth_auth_proto_depIdxs = []int32{
	14, // 0: auth.LoginResponse.joined_projects:type_name -> auth.Project
	15, // 1: auth.LoginResponse.department:type_name -> auth.Department
	12, // 2: auth.LookupTenantByEmailResponse.tenants:type_name -> auth.TenantInfo
	0,  // 3: auth.AuthService.Login:input_type -> auth.LoginRequest
	11, // 4: auth.AuthService.LookupTenantByEmail:input_type -> auth.LookupTenantByEmailRequest
	5,  // 5: auth.AuthService.ValidateToken:input_type -> auth.ValidateTokenRequest
	7,  // 6: auth.AuthService.RefreshToken:input_type -> auth.RefreshTokenRequest
	16, // 7: auth.AuthService.CreateUser:input_type -> auth.CreateUserRequest
	17, // 8: auth.AuthService.BatchCreateUsers:input_type -> auth.BatchCreateUsersRequest
	18, // 9: auth.AuthService.GetUser:input_type -> auth.GetUserRequest
	19, // 10: auth.AuthService.ListUsers:input_type -> auth.ListUsersRequest
	20, // 11: auth.AuthService.UpdateUser:input_type -> auth.UpdateUserRequest
	21, // 12: auth.AuthService.DeleteUser:input_type -> auth.DeleteUserRequest
	22, // 13: auth.AuthService.CreateTenant:input_type -> auth.CreateTenantRequest
	23, // 14: auth.AuthService.GetTenant:input_type -> auth.GetTenantRequest
	24, // 15: auth.AuthService.ListTenants:input_type -> auth.ListTenantsRequest
	25, // 16: auth.AuthService.CreateDepartment:input_type -> auth.CreateDepartmentRequest
	26, // 17: auth.AuthService.BatchCreateDepartments:input_type -> auth.BatchCreateDepartmentsRequest
	27, // 18: auth.AuthService.ListDepartments:input_type -> auth.ListDepartmentsRequest
	28, // 19: auth.AuthService.UpdateDepartment:input_type -> auth.UpdateDepartmentRequest
	29, // 20: auth.AuthService.DeleteDepartment:input_type -> auth.DeleteDepartmentRequest
	30, // 21: auth.AuthService.GetDepartment:input_type -> auth.GetDepartmentRequest
	31, // 22: auth.AuthService.ReorderDepartments:input_type -> auth.ReorderDepartmentsRequest
	32, // 23: auth.AuthService.CreateProject:input_type -> auth.CreateProjectRequest
	33, // 24: auth.AuthService.BatchCreateProjects:input_type -> auth.BatchCreateProjectsRequest
	34, // 25: auth.AuthService.ListProjects:input_type -> auth.ListProjectsRequest
	35, // 26: auth.AuthService.UpdateProject:input_type -> auth.UpdateProjectRequest
	36, // 27: auth.AuthService.DeleteProject:input_type -> auth.DeleteProjectRequest
	37, // 28: auth.AuthService.GetProject:input_type -> auth.GetProjectRequest
	38, // 29: auth.AuthService.ReorderProjects:input_type -> auth.ReorderProjectsRequest
	39, // 30: auth.AuthService.CreatePosition:input_type -> auth.CreatePositionRequest
	40, // 31: auth.AuthService.ListPositions:input_type -> auth.ListPositionsRequest
	41, // 32: auth.AuthService.UpdatePosition:input_type -> auth.UpdatePositionRequest
	42, // 33: auth.AuthService.DeletePosition:input_type -> auth.DeletePositionRequest
	43, // 34: auth.AuthService.ReorderPositions:input_type -> auth.ReorderPositionsRequest
	44, // 35: auth.AuthService.BatchCreatePositions:input_type -> auth.BatchCreatePositionsRequest
	45, // 36: auth.AuthService.CheckAccess:input_type -> auth.CheckAccessRequest
	46, // 37: auth.AuthService.RequestAccess:input_type -> auth.RequestAccessRequest
	47, // 38: auth.AuthService.GrantAccess:input_type -> auth.GrantAccessRequest
	48, // 39: auth.AuthService.ListAccessRequests:input_type -> auth.ListAccessRequestsRequest
	49, // 40: auth.AuthService.CreateDocumentMetadata:input_type -> auth.CreateDocumentMetadataRequest
	50, // 41: auth.AuthService.UpdateDocumentVisibility:input_type -> auth.UpdateDocumentVisibilityRequest
	51, // 42: auth.AuthService.GetDocumentMetadata:input_type -> auth.GetDocumentMetadataRequest
	52, // 43: auth.AuthService.ListVisibilityApprovals:input_type -> auth.ListVisibilityApprovalsRequest
	53, // 44: auth.AuthService.ApproveVisibilityChange:input_type -> auth.ApproveVisibilityChangeRequest
	3,  // 45: auth.AuthService.ResetAndSendPassword:input_type -> auth.ResetAndSendPasswordRequest
	54, // 46: auth.AuthService.BatchResetPassword:input_type -> auth.BatchResetPasswordRequest
	55, // 47: auth.AuthService.ChangePassword:input_type -> auth.ChangePasswordRequest
	9,  // 48: auth.AuthService.Logout:input_type -> auth.LogoutRequest
	2,  // 49: auth.AuthService.Login:output_type -> auth.LoginResponse
	13, // 50: auth.AuthService.LookupTenantByEmail:output_type -> auth.LookupTenantByEmailResponse
	6,  // 51: auth.AuthService.ValidateToken:output_type -> auth.ValidateTokenResponse
	8,  // 52: auth.AuthService.RefreshToken:output_type -> auth.RefreshTokenResponse
	56, // 53: auth.AuthService.CreateUser:output_type -> auth.CreateUserResponse
	57, // 54: auth.AuthService.BatchCreateUsers:output_type -> auth.BatchCreateUsersResponse
	58, // 55: auth.AuthService.GetUser:output_type -> auth.GetUserResponse
	59, // 56: auth.AuthService.ListUsers:output_type -> auth.ListUsersResponse
	60, // 57: auth.AuthService.UpdateUser:output_type -> auth.UpdateUserResponse
	61, // 58: auth.AuthService.DeleteUser:output_type -> auth.DeleteUserResponse
	62, // 59: auth.AuthService.CreateTenant:output_type -> auth.CreateTenantResponse
	63, // 60: auth.AuthService.GetTenant:output_type -> auth.GetTenantResponse
	64, // 61: auth.AuthService.ListTenants:output_type -> auth.ListTenantsResponse
	65, // 62: auth.AuthService.CreateDepartment:output_type -> auth.CreateDepartmentResponse
	66, // 63: auth.AuthService.BatchCreateDepartments:output_type -> auth.BatchCreateDepartmentsResponse
	67, // 64: auth.AuthService.ListDepartments:output_type -> auth.ListDepartmentsResponse
	68, // 65: auth.AuthService.UpdateDepartment:output_type -> auth.UpdateDepartmentResponse
	69, // 66: auth.AuthService.DeleteDepartment:output_type -> auth.DeleteDepartmentResponse
	70, // 67: auth.AuthService.GetDepartment:output_type -> auth.GetDepartmentResponse
	71, // 68: auth.AuthService.ReorderDepartments:output_type -> auth.ReorderDepartmentsResponse
	72, // 69: auth.AuthService.CreateProject:output_type -> auth.CreateProjectResponse
	73, // 70: auth.AuthService.BatchCreateProjects:output_type -> auth.BatchCreateProjectsResponse
	74, // 71: auth.AuthService.ListProjects:output_type -> auth.ListProjectsResponse
	75, // 72: auth.AuthService.UpdateProject:output_type -> auth.UpdateProjectResponse
	76, // 73: auth.AuthService.DeleteProject:output_type -> auth.DeleteProjectResponse
	77, // 74: auth.AuthService.GetProject:output_type -> auth.GetProjectResponse
	78, // 75: auth.AuthService.ReorderProjects:output_type -> auth.ReorderProjectsResponse
	79, // 76: auth.AuthService.CreatePosition:output_type -> auth.CreatePositionResponse
	80, // 77: auth.AuthService.ListPositions:output_type -> auth.ListPositionsResponse
	81, // 78: auth.AuthService.UpdatePosition:output_type -> auth.UpdatePositionResponse
	82, // 79: auth.AuthService.DeletePosition:output_type -> auth.DeletePositionResponse
	83, // 80: auth.AuthService.ReorderPositions:output_type -> auth.ReorderPositionsResponse
	84, // 81: auth.AuthService.BatchCreatePositions:output_type -> auth.BatchCreatePositionsResponse
	85, // 82: auth.AuthService.CheckAccess:output_type -> auth.CheckAccessResponse
	86, // 83: auth.AuthService.RequestAccess:output_type -> auth.RequestAccessResponse
	87, // 84: auth.AuthService.GrantAccess:output_type -> auth.GrantAccessResponse
	88, // 85: auth.AuthService.ListAccessRequests:output_type -> auth.ListAccessRequestsResponse
	89, // 86: auth.AuthService.CreateDocumentMetadata:output_type -> auth.CreateDocumentMetadataResponse
	90, // 87: auth.AuthService.UpdateDocumentVisibility:output_type -> auth.UpdateDocumentVisibilityResponse
	91, // 88: auth.AuthService.GetDocumentMetadata:output_type -> auth.GetDocumentMetadataResponse
	92, // 89: auth.AuthService.ListVisibilityApprovals:output_type -> auth.ListVisibilityApprovalsResponse
	93, // 90: auth.AuthService.ApproveVisibilityChange:output_type -> auth.ApproveVisibilityChangeResponse
	4,  // 91: auth.AuthService.ResetAndSendPassword:output_type -> auth.ResetAndSendPasswordResponse
	94, // 92: auth.AuthService.BatchResetPassword:output_type -> auth.BatchResetPasswordResponse
	95, // 93: auth.AuthService.ChangePassword:output_type -> auth.ChangePasswordResponse
	10, // 94: auth.AuthService.Logout:output_type -> auth.LogoutResponse
	49, // [49:95] is the sub-list for method output_type
	3,  // [3:49] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_auth_auth_proto_init() }
func file_auth_auth_proto_init() {
	if File_auth_auth_proto != nil {
		return
	}
	file_auth_user_proto_init()
	file_auth_tenant_proto_init()
	file_auth_acl_proto_init()
	file_auth_department_proto_init()
	file_auth_project_proto_init()
	file_auth_document_proto_init()
	file_auth_position_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_auth_proto_rawDesc), len(file_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_auth_proto_goTypes,
		DependencyIndexes: file_auth_auth_proto_depIdxs,
		MessageInfos:      file_auth_auth_proto_msgTypes,
	}.Build()
	File_auth_auth_proto = out.File
	file_auth_auth_proto_goTypes = nil
	file_auth_auth_proto_depIdxs = nil
}
