// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: auth/department.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Department Message
type Department struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// description removed
	ManagerId              string          `protobuf:"bytes,4,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	ParentDepartmentId     string          `protobuf:"bytes,5,opt,name=parent_department_id,json=parentDepartmentId,proto3" json:"parent_department_id,omitempty"` // For hierarchy if needed
	CreatedAt              string          `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt              string          `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DefaultVisibilityLevel VisibilityLevel `protobuf:"varint,10,opt,name=default_visibility_level,json=defaultVisibilityLevel,proto3,enum=auth.VisibilityLevel" json:"default_visibility_level,omitempty"`
	SortOrder              int32           `protobuf:"varint,11,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"` // For drag-drop ordering
	// Optional: Manager details for display
	Manager       *User `protobuf:"bytes,8,opt,name=manager,proto3" json:"manager,omitempty"`
	MemberCount   int32 `protobuf:"varint,9,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Department) Reset() {
	*x = Department{}
	mi := &file_auth_department_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Department) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Department) ProtoMessage() {}

func (x *Department) ProtoReflect() protoreflect.Message {
	mi := &file_auth_department_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Department.ProtoReflect.Descriptor instead.
func (*Department) Descriptor() ([]byte, []int) {
	return file_auth_department_proto_rawDescGZIP(), []int{0}
}

func (x *Department) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Department) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Department) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *Department) GetParentDepartmentId() string {
	if x != nil {
		return x.ParentDepartmentId
	}
	return ""
}

func (x *Department) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Department) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Department) GetDefaultVisibilityLevel() VisibilityLevel {
	if x != nil {
		return x.DefaultVisibilityLevel
	}
	return VisibilityLevel_VISIBILITY_LEVEL_UNSPECIFIED
}

func (x *Department) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *Department) GetManager() *User {
	if x != nil {
		return x.Manager
	}
	return nil
}

func (x *Department) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

type CreateDepartmentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// description removed
	ManagerId              string          `protobuf:"bytes,3,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	ParentDepartmentId     string          `protobuf:"bytes,4,opt,name=parent_department_id,json=parentDepartmentId,proto3" json:"parent_department_id,omitempty"`
	TenantId               string          `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // Multi-tenancy
	DefaultVisibilityLevel VisibilityLevel `protobuf:"varint,6,opt,name=default_visibility_level,json=defaultVisibilityLevel,proto3,enum=auth.VisibilityLevel" json:"default_visibility_level,omitempty"`
	Id                     string          `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`                                   // Optional: Allow defining ID during creation (e.g. Bulk Import)
	ParentName             string          `protobuf:"bytes,8,opt,name=parent_name,json=parentName,proto3" json:"parent_name,omitempty"` // Optional: Lookup parent by name if parent_department_id is empty
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateDepartmentRequest) Reset() {
	*x = CreateDepartmentRequest{}
	mi := &file_auth_department_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDepartmentRequest) ProtoMessage() {}

func (x *CreateDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_department_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDepartmentRequest.ProtoReflect.Descriptor instead.
func (*CreateDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_auth_department_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDepartmentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDepartmentRequest) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *CreateDepartmentRequest) GetParentDepartmentId() string {
	if x != nil {
		return x.ParentDepartmentId
	}
	return ""
}

func (x *CreateDepartmentRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateDepartmentRequest) GetDefaultVisibilityLevel() VisibilityLevel {
	if x != nil {
		return x.DefaultVisibilityLevel
	}
	return VisibilityLevel_VISIBILITY_LEVEL_UNSPECIFIED
}

func (x *CreateDepartmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateDepartmentRequest) GetParentName() string {
	if x != nil {
		return x.ParentName
	}
	return ""
}

type CreateDepartmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Department    *Department            `protobuf:"bytes,1,opt,name=department,proto3" json:"department,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDepartmentResponse) Reset() {
	*x = CreateDepartmentResponse{}
	mi := &file_auth_department_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDepartmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDepartmentResponse) ProtoMessage() {}

func (x *CreateDepartmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_department_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDepartmentResponse.ProtoReflect.Descriptor instead.
func (*CreateDepartmentResponse) Descriptor() ([]byte, []int) {
	return file_auth_department_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDepartmentResponse) GetDepartment() *Department {
	if x != nil {
		return x.Department
	}
	return nil
}

type BatchCreateDepartmentsRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	TenantId      string                     `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Requests      []*CreateDepartmentRequest `protobuf:"bytes,2,rep,name=requests,proto3" json:"requests,omitempty"`
	ImportMode    string                     `protobuf:"bytes,3,opt,name=import_mode,json=importMode,proto3" json:"import_mode,omitempty"` // "replace" or "upsert"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateDepartmentsRequest) Reset() {
	*x = BatchCreateDepartmentsRequest{}
	mi := &file_auth_department_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateDepartmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateDepartmentsRequest) ProtoMessage() {}

func (x *BatchCreateDepartmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_department_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateDepartmentsRequest.ProtoReflect.Descriptor instead.
func (*BatchCreateDepartmentsRequest) Descriptor() ([]byte, []int) {
	return file_auth_department_proto_rawDescGZIP(), []int{3}
}

func (x *BatchCreateDepartmentsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *BatchCreateDepartmentsRequest) GetRequests() []*CreateDepartmentRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *BatchCreateDepartmentsRequest) GetImportMode() string {
	if x != nil {
		return x.ImportMode
	}
	return ""
}

type BatchCreateDepartmentsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SuccessCount   int32                  `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailureCount   int32                  `protobuf:"varint,2,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
	FailureReasons []string               `protobuf:"bytes,3,rep,name=failure_reasons,json=failureReasons,proto3" json:"failure_reasons,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchCreateDepartmentsResponse) Reset() {
	*x = BatchCreateDepartmentsResponse{}
	mi := &file_auth_department_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateDepartmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateDepartmentsResponse) ProtoMessage() {}

func (x *BatchCreateDepartmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_department_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateDepartmentsResponse.ProtoReflect.Descriptor instead.
func (*BatchCreateDepartmentsResponse) Descriptor() ([]byte, []int) {
	return file_auth_department_proto_rawDescGZIP(), []int{4}
}

func (x *BatchCreateDepartmentsResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *BatchCreateDepartmentsResponse) GetFailureCount() int32 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

func (x *BatchCreateDepartmentsResponse) GetFailureReasons() []string {
	if x != nil {
		return x.FailureReasons
	}
	return nil
}

type ListDepartmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SearchQuery   string                 `protobuf:"bytes,2,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"` // Optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDepartmentsRequest) Reset() {
	*x = ListDepartmentsRequest{}
	mi := &file_auth_department_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDepartmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDepartmentsRequest) ProtoMessage() {}

func (x *ListDepartmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_department_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDepartmentsRequest.ProtoReflect.Descriptor instead.
func (*ListDepartmentsRequest) Descriptor() ([]byte, []int) {
	return file_auth_department_proto_rawDescGZIP(), []int{5}
}

func (x *ListDepartmentsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListDepartmentsRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

type ListDepartmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Departments   []*Department          `protobuf:"bytes,1,rep,name=departments,proto3" json:"departments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDepartmentsResponse) Reset() {
	*x = ListDepartmentsResponse{}
	mi := &file_auth_department_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDepartmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDepartmentsResponse) ProtoMessage() {}

func (x *ListDepartmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_department_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDepartmentsResponse.ProtoReflect.Descriptor instead.
func (*ListDepartmentsResponse) Descriptor() ([]byte, []int) {
	return file_auth_department_proto_rawDescGZIP(), []int{6}
}

func (x *ListDepartmentsResponse) GetDepartments() []*Department {
	if x != nil {
		return x.Departments
	}
	return nil
}

type UpdateDepartmentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// description removed
	ManagerId              string          `protobuf:"bytes,4,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	ParentDepartmentId     string          `protobuf:"bytes,5,opt,name=parent_department_id,json=parentDepartmentId,proto3" json:"parent_department_id,omitempty"`
	DefaultVisibilityLevel VisibilityLevel `protobuf:"varint,6,opt,name=default_visibility_level,json=defaultVisibilityLevel,proto3,enum=auth.VisibilityLevel" json:"default_visibility_level,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UpdateDepartmentRequest) Reset() {
	*x = UpdateDepartmentRequest{}
	mi := &file_auth_department_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDepartmentRequest) ProtoMessage() {}

func (x *UpdateDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_department_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDepartmentRequest.ProtoReflect.Descriptor instead.
func (*UpdateDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_auth_department_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateDepartmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDepartmentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDepartmentRequest) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *UpdateDepartmentRequest) GetParentDepartmentId() string {
	if x != nil {
		return x.ParentDepartmentId
	}
	return ""
}

func (x *UpdateDepartmentRequest) GetDefaultVisibilityLevel() VisibilityLevel {
	if x != nil {
		return x.DefaultVisibilityLevel
	}
	return VisibilityLevel_VISIBILITY_LEVEL_UNSPECIFIED
}

type UpdateDepartmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Department    *Department            `protobuf:"bytes,1,opt,name=department,proto3" json:"department,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDepartmentResponse) Reset() {
	*x = UpdateDepartmentResponse{}
	mi := &file_auth_department_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDepartmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDepartmentResponse) ProtoMessage() {}

func (x *UpdateDepartmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_department_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDepartmentResponse.ProtoReflect.Descriptor instead.
func (*UpdateDepartmentResponse) Descriptor() ([]byte, []int) {
	return file_auth_department_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateDepartmentResponse) GetDepartment() *Department {
	if x != nil {
		return x.Department
	}
	return nil
}

type DeleteDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDepartmentRequest) Reset() {
	*x = DeleteDepartmentRequest{}
	mi := &file_auth_department_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDepartmentRequest) ProtoMessage() {}

func (x *DeleteDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_department_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDepartmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_auth_department_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteDepartmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteDepartmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDepartmentResponse) Reset() {
	*x = DeleteDepartmentResponse{}
	mi := &file_auth_department_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDepartmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDepartmentResponse) ProtoMessage() {}

func (x *DeleteDepartmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_department_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDepartmentResponse.ProtoReflect.Descriptor instead.
func (*DeleteDepartmentResponse) Descriptor() ([]byte, []int) {
	return file_auth_department_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteDepartmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// GetDepartment used for details view
type GetDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepartmentRequest) Reset() {
	*x = GetDepartmentRequest{}
	mi := &file_auth_department_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepartmentRequest) ProtoMessage() {}

func (x *GetDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_department_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepartmentRequest.ProtoReflect.Descriptor instead.
func (*GetDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_auth_department_proto_rawDescGZIP(), []int{11}
}

func (x *GetDepartmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDepartmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Department    *Department            `protobuf:"bytes,1,opt,name=department,proto3" json:"department,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepartmentResponse) Reset() {
	*x = GetDepartmentResponse{}
	mi := &file_auth_department_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepartmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepartmentResponse) ProtoMessage() {}

func (x *GetDepartmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_department_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepartmentResponse.ProtoReflect.Descriptor instead.
func (*GetDepartmentResponse) Descriptor() ([]byte, []int) {
	return file_auth_department_proto_rawDescGZIP(), []int{12}
}

func (x *GetDepartmentResponse) GetDepartment() *Department {
	if x != nil {
		return x.Department
	}
	return nil
}

// Reorder departments (drag-drop)
type DepartmentOrderItem struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentDepartmentId string                 `protobuf:"bytes,2,opt,name=parent_department_id,json=parentDepartmentId,proto3" json:"parent_department_id,omitempty"` // Empty for root
	SortOrder          int32                  `protobuf:"varint,3,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DepartmentOrderItem) Reset() {
	*x = DepartmentOrderItem{}
	mi := &file_auth_department_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepartmentOrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartmentOrderItem) ProtoMessage() {}

func (x *DepartmentOrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_auth_department_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartmentOrderItem.ProtoReflect.Descriptor instead.
func (*DepartmentOrderItem) Descriptor() ([]byte, []int) {
	return file_auth_department_proto_rawDescGZIP(), []int{13}
}

func (x *DepartmentOrderItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DepartmentOrderItem) GetParentDepartmentId() string {
	if x != nil {
		return x.ParentDepartmentId
	}
	return ""
}

func (x *DepartmentOrderItem) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type ReorderDepartmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Items         []*DepartmentOrderItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReorderDepartmentsRequest) Reset() {
	*x = ReorderDepartmentsRequest{}
	mi := &file_auth_department_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderDepartmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderDepartmentsRequest) ProtoMessage() {}

func (x *ReorderDepartmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_department_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderDepartmentsRequest.ProtoReflect.Descriptor instead.
func (*ReorderDepartmentsRequest) Descriptor() ([]byte, []int) {
	return file_auth_department_proto_rawDescGZIP(), []int{14}
}

func (x *ReorderDepartmentsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ReorderDepartmentsRequest) GetItems() []*DepartmentOrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReorderDepartmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReorderDepartmentsResponse) Reset() {
	*x = ReorderDepartmentsResponse{}
	mi := &file_auth_department_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderDepartmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderDepartmentsResponse) ProtoMessage() {}

func (x *ReorderDepartmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_department_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderDepartmentsResponse.ProtoReflect.Descriptor instead.
func (*ReorderDepartmentsResponse) Descriptor() ([]byte, []int) {
	return file_auth_department_proto_rawDescGZIP(), []int{15}
}

func (x *ReorderDepartmentsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_auth_department_proto protoreflect.FileDescriptor

const file_auth_department_proto_rawDesc = "" +
	"\n" +
	"\x15auth/department.proto\x12\x04auth\x1a\x0fauth/user.proto\x1a\x0eauth/acl.proto\"\xf8\x02\n" +
	"\n" +
	"Department\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x04 \x01(\tR\tmanagerId\x120\n" +
	"\x14parent_department_id\x18\x05 \x01(\tR\x12parentDepartmentId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12O\n" +
	"\x18default_visibility_level\x18\n" +
	" \x01(\x0e2\x15.auth.VisibilityLevelR\x16defaultVisibilityLevel\x12\x1d\n" +
	"\n" +
	"sort_order\x18\v \x01(\x05R\tsortOrder\x12$\n" +
	"\amanager\x18\b \x01(\v2\n" +
	".auth.UserR\amanager\x12!\n" +
	"\fmember_count\x18\t \x01(\x05R\vmemberCount\"\x9d\x02\n" +
	"\x17CreateDepartmentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x03 \x01(\tR\tmanagerId\x120\n" +
	"\x14parent_department_id\x18\x04 \x01(\tR\x12parentDepartmentId\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\x12O\n" +
	"\x18default_visibility_level\x18\x06 \x01(\x0e2\x15.auth.VisibilityLevelR\x16defaultVisibilityLevel\x12\x0e\n" +
	"\x02id\x18\a \x01(\tR\x02id\x12\x1f\n" +
	"\vparent_name\x18\b \x01(\tR\n" +
	"parentName\"L\n" +
	"\x18CreateDepartmentResponse\x120\n" +
	"\n" +
	"department\x18\x01 \x01(\v2\x10.auth.DepartmentR\n" +
	"department\"\x98\x01\n" +
	"\x1dBatchCreateDepartmentsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x129\n" +
	"\brequests\x18\x02 \x03(\v2\x1d.auth.CreateDepartmentRequestR\brequests\x12\x1f\n" +
	"\vimport_mode\x18\x03 \x01(\tR\n" +
	"importMode\"\x93\x01\n" +
	"\x1eBatchCreateDepartmentsResponse\x12#\n" +
	"\rsuccess_count\x18\x01 \x01(\x05R\fsuccessCount\x12#\n" +
	"\rfailure_count\x18\x02 \x01(\x05R\ffailureCount\x12'\n" +
	"\x0ffailure_reasons\x18\x03 \x03(\tR\x0efailureReasons\"X\n" +
	"\x16ListDepartmentsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12!\n" +
	"\fsearch_query\x18\x02 \x01(\tR\vsearchQuery\"M\n" +
	"\x17ListDepartmentsResponse\x122\n" +
	"\vdepartments\x18\x01 \x03(\v2\x10.auth.DepartmentR\vdepartments\"\xdf\x01\n" +
	"\x17UpdateDepartmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x04 \x01(\tR\tmanagerId\x120\n" +
	"\x14parent_department_id\x18\x05 \x01(\tR\x12parentDepartmentId\x12O\n" +
	"\x18default_visibility_level\x18\x06 \x01(\x0e2\x15.auth.VisibilityLevelR\x16defaultVisibilityLevel\"L\n" +
	"\x18UpdateDepartmentResponse\x120\n" +
	"\n" +
	"department\x18\x01 \x01(\v2\x10.auth.DepartmentR\n" +
	"department\")\n" +
	"\x17DeleteDepartmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"4\n" +
	"\x18DeleteDepartmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"&\n" +
	"\x14GetDepartmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"I\n" +
	"\x15GetDepartmentResponse\x120\n" +
	"\n" +
	"department\x18\x01 \x01(\v2\x10.auth.DepartmentR\n" +
	"department\"v\n" +
	"\x13DepartmentOrderItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x14parent_department_id\x18\x02 \x01(\tR\x12parentDepartmentId\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x03 \x01(\x05R\tsortOrder\"i\n" +
	"\x19ReorderDepartmentsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12/\n" +
	"\x05items\x18\x02 \x03(\v2\x19.auth.DepartmentOrderItemR\x05items\"6\n" +
	"\x1aReorderDepartmentsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccessB\x15Z\x13server/.protos/authb\x06proto3"

var (
	file_auth_department_proto_rawDescOnce sync.Once
	file_auth_department_proto_rawDescData []byte
)

func file_auth_department_proto_rawDescGZIP() []byte {
	file_auth_department_proto_rawDescOnce.Do(func() {
		file_auth_department_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_department_proto_rawDesc), len(file_auth_department_proto_rawDesc)))
	})
	return file_auth_department_proto_rawDescData
}

var file_auth_department_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_auth_department_proto_goTypes = []any{
	(*Department)(nil),                     // 0: auth.Department
	(*CreateDepartmentRequest)(nil),        // 1: auth.CreateDepartmentRequest
	(*CreateDepartmentResponse)(nil),       // 2: auth.CreateDepartmentResponse
	(*BatchCreateDepartmentsRequest)(nil),  // 3: auth.BatchCreateDepartmentsRequest
	(*BatchCreateDepartmentsResponse)(nil), // 4: auth.BatchCreateDepartmentsResponse
	(*ListDepartmentsRequest)(nil),         // 5: auth.ListDepartmentsRequest
	(*ListDepartmentsResponse)(nil),        // 6: auth.ListDepartmentsResponse
	(*UpdateDepartmentRequest)(nil),        // 7: auth.UpdateDepartmentRequest
	(*UpdateDepartmentResponse)(nil),       // 8: auth.UpdateDepartmentResponse
	(*DeleteDepartmentRequest)(nil),        // 9: auth.DeleteDepartmentRequest
	(*DeleteDepartmentResponse)(nil),       // 10: auth.DeleteDepartmentResponse
	(*GetDepartmentRequest)(nil),           // 11: auth.GetDepartmentRequest
	(*GetDepartmentResponse)(nil),          // 12: auth.GetDepartmentResponse
	(*DepartmentOrderItem)(nil),            // 13: auth.DepartmentOrderItem
	(*ReorderDepartmentsRequest)(nil),      // 14: auth.ReorderDepartmentsRequest
	(*ReorderDepartmentsResponse)(nil),     // 15: auth.ReorderDepartmentsResponse
	(VisibilityLevel)(0),                   // 16: auth.VisibilityLevel
	(*User)(nil),                           // 17: auth.User
}
var file_auth_department_proto_depIdxs = []int32{
	16, // 0: auth.Department.default_visibility_level:type_name -> auth.VisibilityLevel
	17, // 1: auth.Department.manager:type_name -> auth.User
	16, // 2: auth.CreateDepartmentRequest.default_visibility_level:type_name -> auth.VisibilityLevel
	0,  // 3: auth.CreateDepartmentResponse.department:type_name -> auth.Department
	1,  // 4: auth.BatchCreateDepartmentsRequest.requests:type_name -> auth.CreateDepartmentRequest
	0,  // 5: auth.ListDepartmentsResponse.departments:type_name -> auth.Department
	16, // 6: auth.UpdateDepartmentRequest.default_visibility_level:type_name -> auth.VisibilityLevel
	0,  // 7: auth.UpdateDepartmentResponse.department:type_name -> auth.Department
	0,  // 8: auth.GetDepartmentResponse.department:type_name -> auth.Department
	13, // 9: auth.ReorderDepartmentsRequest.items:type_name -> auth.DepartmentOrderItem
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_auth_department_proto_init() }
func file_auth_department_proto_init() {
	if File_auth_department_proto != nil {
		return
	}
	file_auth_user_proto_init()
	file_auth_acl_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_department_proto_rawDesc), len(file_auth_department_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_department_proto_goTypes,
		DependencyIndexes: file_auth_department_proto_depIdxs,
		MessageInfos:      file_auth_department_proto_msgTypes,
	}.Build()
	File_auth_department_proto = out.File
	file_auth_department_proto_goTypes = nil
	file_auth_department_proto_depIdxs = nil
}
