// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: auth/document.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DocumentMetadata Message (Stored in Auth Service for ACL)
type DocumentMetadata struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId               string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	DepartmentId          string                 `protobuf:"bytes,3,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	Title                 string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	SearchVisibilityLevel VisibilityLevel        `protobuf:"varint,5,opt,name=search_visibility_level,json=searchVisibilityLevel,proto3,enum=auth.VisibilityLevel" json:"search_visibility_level,omitempty"`
	IsPrivate             bool                   `protobuf:"varint,6,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	ApprovalStatus        string                 `protobuf:"bytes,7,opt,name=approval_status,json=approvalStatus,proto3" json:"approval_status,omitempty"` // none, pending, approved, rejected
	CreatedAt             string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt             string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DocumentMetadata) Reset() {
	*x = DocumentMetadata{}
	mi := &file_auth_document_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentMetadata) ProtoMessage() {}

func (x *DocumentMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_auth_document_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentMetadata.ProtoReflect.Descriptor instead.
func (*DocumentMetadata) Descriptor() ([]byte, []int) {
	return file_auth_document_proto_rawDescGZIP(), []int{0}
}

func (x *DocumentMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DocumentMetadata) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *DocumentMetadata) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

func (x *DocumentMetadata) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DocumentMetadata) GetSearchVisibilityLevel() VisibilityLevel {
	if x != nil {
		return x.SearchVisibilityLevel
	}
	return VisibilityLevel_VISIBILITY_LEVEL_UNSPECIFIED
}

func (x *DocumentMetadata) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *DocumentMetadata) GetApprovalStatus() string {
	if x != nil {
		return x.ApprovalStatus
	}
	return ""
}

func (x *DocumentMetadata) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *DocumentMetadata) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateDocumentMetadataRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Optional, can be auto-generated or passed from Index Service
	OwnerId               string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	DepartmentId          string                 `protobuf:"bytes,3,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	Title                 string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	SearchVisibilityLevel VisibilityLevel        `protobuf:"varint,5,opt,name=search_visibility_level,json=searchVisibilityLevel,proto3,enum=auth.VisibilityLevel" json:"search_visibility_level,omitempty"` // Initial level
	IsPrivate             bool                   `protobuf:"varint,6,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateDocumentMetadataRequest) Reset() {
	*x = CreateDocumentMetadataRequest{}
	mi := &file_auth_document_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDocumentMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDocumentMetadataRequest) ProtoMessage() {}

func (x *CreateDocumentMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_document_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDocumentMetadataRequest.ProtoReflect.Descriptor instead.
func (*CreateDocumentMetadataRequest) Descriptor() ([]byte, []int) {
	return file_auth_document_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDocumentMetadataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateDocumentMetadataRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateDocumentMetadataRequest) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

func (x *CreateDocumentMetadataRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateDocumentMetadataRequest) GetSearchVisibilityLevel() VisibilityLevel {
	if x != nil {
		return x.SearchVisibilityLevel
	}
	return VisibilityLevel_VISIBILITY_LEVEL_UNSPECIFIED
}

func (x *CreateDocumentMetadataRequest) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

type CreateDocumentMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *DocumentMetadata      `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDocumentMetadataResponse) Reset() {
	*x = CreateDocumentMetadataResponse{}
	mi := &file_auth_document_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDocumentMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDocumentMetadataResponse) ProtoMessage() {}

func (x *CreateDocumentMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_document_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDocumentMetadataResponse.ProtoReflect.Descriptor instead.
func (*CreateDocumentMetadataResponse) Descriptor() ([]byte, []int) {
	return file_auth_document_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDocumentMetadataResponse) GetDocument() *DocumentMetadata {
	if x != nil {
		return x.Document
	}
	return nil
}

type UpdateDocumentVisibilityRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DocumentId         string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	NewVisibilityLevel VisibilityLevel        `protobuf:"varint,2,opt,name=new_visibility_level,json=newVisibilityLevel,proto3,enum=auth.VisibilityLevel" json:"new_visibility_level,omitempty"`
	IsPrivate          bool                   `protobuf:"varint,3,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	RequesterId        string                 `protobuf:"bytes,4,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"` // Used to check permission and dept default
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateDocumentVisibilityRequest) Reset() {
	*x = UpdateDocumentVisibilityRequest{}
	mi := &file_auth_document_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocumentVisibilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocumentVisibilityRequest) ProtoMessage() {}

func (x *UpdateDocumentVisibilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_document_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocumentVisibilityRequest.ProtoReflect.Descriptor instead.
func (*UpdateDocumentVisibilityRequest) Descriptor() ([]byte, []int) {
	return file_auth_document_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateDocumentVisibilityRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *UpdateDocumentVisibilityRequest) GetNewVisibilityLevel() VisibilityLevel {
	if x != nil {
		return x.NewVisibilityLevel
	}
	return VisibilityLevel_VISIBILITY_LEVEL_UNSPECIFIED
}

func (x *UpdateDocumentVisibilityRequest) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *UpdateDocumentVisibilityRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

type UpdateDocumentVisibilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                           // "applied", "pending_approval"
	ApprovalId    string                 `protobuf:"bytes,3,opt,name=approval_id,json=approvalId,proto3" json:"approval_id,omitempty"` // If pending
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDocumentVisibilityResponse) Reset() {
	*x = UpdateDocumentVisibilityResponse{}
	mi := &file_auth_document_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocumentVisibilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocumentVisibilityResponse) ProtoMessage() {}

func (x *UpdateDocumentVisibilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_document_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocumentVisibilityResponse.ProtoReflect.Descriptor instead.
func (*UpdateDocumentVisibilityResponse) Descriptor() ([]byte, []int) {
	return file_auth_document_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateDocumentVisibilityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateDocumentVisibilityResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateDocumentVisibilityResponse) GetApprovalId() string {
	if x != nil {
		return x.ApprovalId
	}
	return ""
}

type GetDocumentMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentMetadataRequest) Reset() {
	*x = GetDocumentMetadataRequest{}
	mi := &file_auth_document_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentMetadataRequest) ProtoMessage() {}

func (x *GetDocumentMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_document_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentMetadataRequest) Descriptor() ([]byte, []int) {
	return file_auth_document_proto_rawDescGZIP(), []int{5}
}

func (x *GetDocumentMetadataRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type GetDocumentMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *DocumentMetadata      `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentMetadataResponse) Reset() {
	*x = GetDocumentMetadataResponse{}
	mi := &file_auth_document_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentMetadataResponse) ProtoMessage() {}

func (x *GetDocumentMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_document_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetDocumentMetadataResponse) Descriptor() ([]byte, []int) {
	return file_auth_document_proto_rawDescGZIP(), []int{6}
}

func (x *GetDocumentMetadataResponse) GetDocument() *DocumentMetadata {
	if x != nil {
		return x.Document
	}
	return nil
}

var File_auth_document_proto protoreflect.FileDescriptor

const file_auth_document_proto_rawDesc = "" +
	"\n" +
	"\x13auth/document.proto\x12\x04auth\x1a\x0eauth/acl.proto\"\xcd\x02\n" +
	"\x10DocumentMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12#\n" +
	"\rdepartment_id\x18\x03 \x01(\tR\fdepartmentId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12M\n" +
	"\x17search_visibility_level\x18\x05 \x01(\x0e2\x15.auth.VisibilityLevelR\x15searchVisibilityLevel\x12\x1d\n" +
	"\n" +
	"is_private\x18\x06 \x01(\bR\tisPrivate\x12'\n" +
	"\x0fapproval_status\x18\a \x01(\tR\x0eapprovalStatus\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"\xf3\x01\n" +
	"\x1dCreateDocumentMetadataRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12#\n" +
	"\rdepartment_id\x18\x03 \x01(\tR\fdepartmentId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12M\n" +
	"\x17search_visibility_level\x18\x05 \x01(\x0e2\x15.auth.VisibilityLevelR\x15searchVisibilityLevel\x12\x1d\n" +
	"\n" +
	"is_private\x18\x06 \x01(\bR\tisPrivate\"T\n" +
	"\x1eCreateDocumentMetadataResponse\x122\n" +
	"\bdocument\x18\x01 \x01(\v2\x16.auth.DocumentMetadataR\bdocument\"\xcd\x01\n" +
	"\x1fUpdateDocumentVisibilityRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12G\n" +
	"\x14new_visibility_level\x18\x02 \x01(\x0e2\x15.auth.VisibilityLevelR\x12newVisibilityLevel\x12\x1d\n" +
	"\n" +
	"is_private\x18\x03 \x01(\bR\tisPrivate\x12!\n" +
	"\frequester_id\x18\x04 \x01(\tR\vrequesterId\"u\n" +
	" UpdateDocumentVisibilityResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vapproval_id\x18\x03 \x01(\tR\n" +
	"approvalId\"=\n" +
	"\x1aGetDocumentMetadataRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\"Q\n" +
	"\x1bGetDocumentMetadataResponse\x122\n" +
	"\bdocument\x18\x01 \x01(\v2\x16.auth.DocumentMetadataR\bdocumentB\x15Z\x13server/.protos/authb\x06proto3"

var (
	file_auth_document_proto_rawDescOnce sync.Once
	file_auth_document_proto_rawDescData []byte
)

func file_auth_document_proto_rawDescGZIP() []byte {
	file_auth_document_proto_rawDescOnce.Do(func() {
		file_auth_document_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_document_proto_rawDesc), len(file_auth_document_proto_rawDesc)))
	})
	return file_auth_document_proto_rawDescData
}

var file_auth_document_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_auth_document_proto_goTypes = []any{
	(*DocumentMetadata)(nil),                 // 0: auth.DocumentMetadata
	(*CreateDocumentMetadataRequest)(nil),    // 1: auth.CreateDocumentMetadataRequest
	(*CreateDocumentMetadataResponse)(nil),   // 2: auth.CreateDocumentMetadataResponse
	(*UpdateDocumentVisibilityRequest)(nil),  // 3: auth.UpdateDocumentVisibilityRequest
	(*UpdateDocumentVisibilityResponse)(nil), // 4: auth.UpdateDocumentVisibilityResponse
	(*GetDocumentMetadataRequest)(nil),       // 5: auth.GetDocumentMetadataRequest
	(*GetDocumentMetadataResponse)(nil),      // 6: auth.GetDocumentMetadataResponse
	(VisibilityLevel)(0),                     // 7: auth.VisibilityLevel
}
var file_auth_document_proto_depIdxs = []int32{
	7, // 0: auth.DocumentMetadata.search_visibility_level:type_name -> auth.VisibilityLevel
	7, // 1: auth.CreateDocumentMetadataRequest.search_visibility_level:type_name -> auth.VisibilityLevel
	0, // 2: auth.CreateDocumentMetadataResponse.document:type_name -> auth.DocumentMetadata
	7, // 3: auth.UpdateDocumentVisibilityRequest.new_visibility_level:type_name -> auth.VisibilityLevel
	0, // 4: auth.GetDocumentMetadataResponse.document:type_name -> auth.DocumentMetadata
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_auth_document_proto_init() }
func file_auth_document_proto_init() {
	if File_auth_document_proto != nil {
		return
	}
	file_auth_acl_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_document_proto_rawDesc), len(file_auth_document_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_document_proto_goTypes,
		DependencyIndexes: file_auth_document_proto_depIdxs,
		MessageInfos:      file_auth_document_proto_msgTypes,
	}.Build()
	File_auth_document_proto = out.File
	file_auth_document_proto_goTypes = nil
	file_auth_document_proto_depIdxs = nil
}
