// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: auth/position.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Order         int32                  `protobuf:"varint,4,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_auth_position_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_auth_position_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_auth_position_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Position) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Position) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Position) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

// Position Requests
type CreatePositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePositionRequest) Reset() {
	*x = CreatePositionRequest{}
	mi := &file_auth_position_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePositionRequest) ProtoMessage() {}

func (x *CreatePositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_position_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePositionRequest.ProtoReflect.Descriptor instead.
func (*CreatePositionRequest) Descriptor() ([]byte, []int) {
	return file_auth_position_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePositionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreatePositionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreatePositionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *Position              `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePositionResponse) Reset() {
	*x = CreatePositionResponse{}
	mi := &file_auth_position_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePositionResponse) ProtoMessage() {}

func (x *CreatePositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_position_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePositionResponse.ProtoReflect.Descriptor instead.
func (*CreatePositionResponse) Descriptor() ([]byte, []int) {
	return file_auth_position_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePositionResponse) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type ListPositionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPositionsRequest) Reset() {
	*x = ListPositionsRequest{}
	mi := &file_auth_position_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPositionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPositionsRequest) ProtoMessage() {}

func (x *ListPositionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_position_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPositionsRequest.ProtoReflect.Descriptor instead.
func (*ListPositionsRequest) Descriptor() ([]byte, []int) {
	return file_auth_position_proto_rawDescGZIP(), []int{3}
}

func (x *ListPositionsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ListPositionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*Position            `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPositionsResponse) Reset() {
	*x = ListPositionsResponse{}
	mi := &file_auth_position_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPositionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPositionsResponse) ProtoMessage() {}

func (x *ListPositionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_position_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPositionsResponse.ProtoReflect.Descriptor instead.
func (*ListPositionsResponse) Descriptor() ([]byte, []int) {
	return file_auth_position_proto_rawDescGZIP(), []int{4}
}

func (x *ListPositionsResponse) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

type UpdatePositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePositionRequest) Reset() {
	*x = UpdatePositionRequest{}
	mi := &file_auth_position_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePositionRequest) ProtoMessage() {}

func (x *UpdatePositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_position_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePositionRequest.ProtoReflect.Descriptor instead.
func (*UpdatePositionRequest) Descriptor() ([]byte, []int) {
	return file_auth_position_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePositionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePositionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdatePositionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *Position              `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePositionResponse) Reset() {
	*x = UpdatePositionResponse{}
	mi := &file_auth_position_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePositionResponse) ProtoMessage() {}

func (x *UpdatePositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_position_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePositionResponse.ProtoReflect.Descriptor instead.
func (*UpdatePositionResponse) Descriptor() ([]byte, []int) {
	return file_auth_position_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePositionResponse) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type DeletePositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePositionRequest) Reset() {
	*x = DeletePositionRequest{}
	mi := &file_auth_position_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePositionRequest) ProtoMessage() {}

func (x *DeletePositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_position_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePositionRequest.ProtoReflect.Descriptor instead.
func (*DeletePositionRequest) Descriptor() ([]byte, []int) {
	return file_auth_position_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePositionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePositionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePositionResponse) Reset() {
	*x = DeletePositionResponse{}
	mi := &file_auth_position_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePositionResponse) ProtoMessage() {}

func (x *DeletePositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_position_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePositionResponse.ProtoReflect.Descriptor instead.
func (*DeletePositionResponse) Descriptor() ([]byte, []int) {
	return file_auth_position_proto_rawDescGZIP(), []int{8}
}

func (x *DeletePositionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ReorderPositionItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Order         int32                  `protobuf:"varint,2,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReorderPositionItem) Reset() {
	*x = ReorderPositionItem{}
	mi := &file_auth_position_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderPositionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderPositionItem) ProtoMessage() {}

func (x *ReorderPositionItem) ProtoReflect() protoreflect.Message {
	mi := &file_auth_position_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderPositionItem.ProtoReflect.Descriptor instead.
func (*ReorderPositionItem) Descriptor() ([]byte, []int) {
	return file_auth_position_proto_rawDescGZIP(), []int{9}
}

func (x *ReorderPositionItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReorderPositionItem) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

type ReorderPositionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Items         []*ReorderPositionItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReorderPositionsRequest) Reset() {
	*x = ReorderPositionsRequest{}
	mi := &file_auth_position_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderPositionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderPositionsRequest) ProtoMessage() {}

func (x *ReorderPositionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_position_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderPositionsRequest.ProtoReflect.Descriptor instead.
func (*ReorderPositionsRequest) Descriptor() ([]byte, []int) {
	return file_auth_position_proto_rawDescGZIP(), []int{10}
}

func (x *ReorderPositionsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ReorderPositionsRequest) GetItems() []*ReorderPositionItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReorderPositionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReorderPositionsResponse) Reset() {
	*x = ReorderPositionsResponse{}
	mi := &file_auth_position_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderPositionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderPositionsResponse) ProtoMessage() {}

func (x *ReorderPositionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_position_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderPositionsResponse.ProtoReflect.Descriptor instead.
func (*ReorderPositionsResponse) Descriptor() ([]byte, []int) {
	return file_auth_position_proto_rawDescGZIP(), []int{11}
}

func (x *ReorderPositionsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type BatchCreatePositionsRequest struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	TenantId      string                                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Requests      []*BatchCreatePositionsRequest_Request `protobuf:"bytes,2,rep,name=requests,proto3" json:"requests,omitempty"`
	ImportMode    string                                 `protobuf:"bytes,3,opt,name=import_mode,json=importMode,proto3" json:"import_mode,omitempty"` // "upsert" or "replace"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreatePositionsRequest) Reset() {
	*x = BatchCreatePositionsRequest{}
	mi := &file_auth_position_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreatePositionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreatePositionsRequest) ProtoMessage() {}

func (x *BatchCreatePositionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_position_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreatePositionsRequest.ProtoReflect.Descriptor instead.
func (*BatchCreatePositionsRequest) Descriptor() ([]byte, []int) {
	return file_auth_position_proto_rawDescGZIP(), []int{12}
}

func (x *BatchCreatePositionsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *BatchCreatePositionsRequest) GetRequests() []*BatchCreatePositionsRequest_Request {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *BatchCreatePositionsRequest) GetImportMode() string {
	if x != nil {
		return x.ImportMode
	}
	return ""
}

type BatchCreatePositionsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SuccessCount   int32                  `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailureCount   int32                  `protobuf:"varint,2,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
	FailureReasons []string               `protobuf:"bytes,3,rep,name=failure_reasons,json=failureReasons,proto3" json:"failure_reasons,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchCreatePositionsResponse) Reset() {
	*x = BatchCreatePositionsResponse{}
	mi := &file_auth_position_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreatePositionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreatePositionsResponse) ProtoMessage() {}

func (x *BatchCreatePositionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_position_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreatePositionsResponse.ProtoReflect.Descriptor instead.
func (*BatchCreatePositionsResponse) Descriptor() ([]byte, []int) {
	return file_auth_position_proto_rawDescGZIP(), []int{13}
}

func (x *BatchCreatePositionsResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *BatchCreatePositionsResponse) GetFailureCount() int32 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

func (x *BatchCreatePositionsResponse) GetFailureReasons() []string {
	if x != nil {
		return x.FailureReasons
	}
	return nil
}

type BatchCreatePositionsRequest_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreatePositionsRequest_Request) Reset() {
	*x = BatchCreatePositionsRequest_Request{}
	mi := &file_auth_position_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreatePositionsRequest_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreatePositionsRequest_Request) ProtoMessage() {}

func (x *BatchCreatePositionsRequest_Request) ProtoReflect() protoreflect.Message {
	mi := &file_auth_position_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreatePositionsRequest_Request.ProtoReflect.Descriptor instead.
func (*BatchCreatePositionsRequest_Request) Descriptor() ([]byte, []int) {
	return file_auth_position_proto_rawDescGZIP(), []int{12, 0}
}

func (x *BatchCreatePositionsRequest_Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_auth_position_proto protoreflect.FileDescriptor

const file_auth_position_proto_rawDesc = "" +
	"\n" +
	"\x13auth/position.proto\x12\x04auth\"a\n" +
	"\bPosition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05order\x18\x04 \x01(\x05R\x05order\"H\n" +
	"\x15CreatePositionRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"D\n" +
	"\x16CreatePositionResponse\x12*\n" +
	"\bposition\x18\x01 \x01(\v2\x0e.auth.PositionR\bposition\"3\n" +
	"\x14ListPositionsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"E\n" +
	"\x15ListPositionsResponse\x12,\n" +
	"\tpositions\x18\x01 \x03(\v2\x0e.auth.PositionR\tpositions\";\n" +
	"\x15UpdatePositionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"D\n" +
	"\x16UpdatePositionResponse\x12*\n" +
	"\bposition\x18\x01 \x01(\v2\x0e.auth.PositionR\bposition\"'\n" +
	"\x15DeletePositionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x16DeletePositionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\";\n" +
	"\x13ReorderPositionItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05order\x18\x02 \x01(\x05R\x05order\"g\n" +
	"\x17ReorderPositionsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12/\n" +
	"\x05items\x18\x02 \x03(\v2\x19.auth.ReorderPositionItemR\x05items\"4\n" +
	"\x18ReorderPositionsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xc1\x01\n" +
	"\x1bBatchCreatePositionsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12E\n" +
	"\brequests\x18\x02 \x03(\v2).auth.BatchCreatePositionsRequest.RequestR\brequests\x12\x1f\n" +
	"\vimport_mode\x18\x03 \x01(\tR\n" +
	"importMode\x1a\x1d\n" +
	"\aRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x91\x01\n" +
	"\x1cBatchCreatePositionsResponse\x12#\n" +
	"\rsuccess_count\x18\x01 \x01(\x05R\fsuccessCount\x12#\n" +
	"\rfailure_count\x18\x02 \x01(\x05R\ffailureCount\x12'\n" +
	"\x0ffailure_reasons\x18\x03 \x03(\tR\x0efailureReasonsB\x15Z\x13server/.protos/authb\x06proto3"

var (
	file_auth_position_proto_rawDescOnce sync.Once
	file_auth_position_proto_rawDescData []byte
)

func file_auth_position_proto_rawDescGZIP() []byte {
	file_auth_position_proto_rawDescOnce.Do(func() {
		file_auth_position_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_position_proto_rawDesc), len(file_auth_position_proto_rawDesc)))
	})
	return file_auth_position_proto_rawDescData
}

var file_auth_position_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_auth_position_proto_goTypes = []any{
	(*Position)(nil),                            // 0: auth.Position
	(*CreatePositionRequest)(nil),               // 1: auth.CreatePositionRequest
	(*CreatePositionResponse)(nil),              // 2: auth.CreatePositionResponse
	(*ListPositionsRequest)(nil),                // 3: auth.ListPositionsRequest
	(*ListPositionsResponse)(nil),               // 4: auth.ListPositionsResponse
	(*UpdatePositionRequest)(nil),               // 5: auth.UpdatePositionRequest
	(*UpdatePositionResponse)(nil),              // 6: auth.UpdatePositionResponse
	(*DeletePositionRequest)(nil),               // 7: auth.DeletePositionRequest
	(*DeletePositionResponse)(nil),              // 8: auth.DeletePositionResponse
	(*ReorderPositionItem)(nil),                 // 9: auth.ReorderPositionItem
	(*ReorderPositionsRequest)(nil),             // 10: auth.ReorderPositionsRequest
	(*ReorderPositionsResponse)(nil),            // 11: auth.ReorderPositionsResponse
	(*BatchCreatePositionsRequest)(nil),         // 12: auth.BatchCreatePositionsRequest
	(*BatchCreatePositionsResponse)(nil),        // 13: auth.BatchCreatePositionsResponse
	(*BatchCreatePositionsRequest_Request)(nil), // 14: auth.BatchCreatePositionsRequest.Request
}
var file_auth_position_proto_depIdxs = []int32{
	0,  // 0: auth.CreatePositionResponse.position:type_name -> auth.Position
	0,  // 1: auth.ListPositionsResponse.positions:type_name -> auth.Position
	0,  // 2: auth.UpdatePositionResponse.position:type_name -> auth.Position
	9,  // 3: auth.ReorderPositionsRequest.items:type_name -> auth.ReorderPositionItem
	14, // 4: auth.BatchCreatePositionsRequest.requests:type_name -> auth.BatchCreatePositionsRequest.Request
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_auth_position_proto_init() }
func file_auth_position_proto_init() {
	if File_auth_position_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_position_proto_rawDesc), len(file_auth_position_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_position_proto_goTypes,
		DependencyIndexes: file_auth_position_proto_depIdxs,
		MessageInfos:      file_auth_position_proto_msgTypes,
	}.Build()
	File_auth_position_proto = out.File
	file_auth_position_proto_goTypes = nil
	file_auth_position_proto_depIdxs = nil
}
