// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: auth/project.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Project Message
type Project struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ManagerId   string                 `protobuf:"bytes,4,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	// No hierarchy
	CreatedAt              string          `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt              string          `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DefaultVisibilityLevel VisibilityLevel `protobuf:"varint,10,opt,name=default_visibility_level,json=defaultVisibilityLevel,proto3,enum=auth.VisibilityLevel" json:"default_visibility_level,omitempty"`
	SortOrder              int32           `protobuf:"varint,11,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"` // For drag-drop ordering (flat list)
	// Optional: Manager details for display
	Manager       *User `protobuf:"bytes,8,opt,name=manager,proto3" json:"manager,omitempty"`
	MemberCount   int32 `protobuf:"varint,9,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_auth_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_auth_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_auth_project_proto_rawDescGZIP(), []int{0}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Project) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *Project) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Project) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Project) GetDefaultVisibilityLevel() VisibilityLevel {
	if x != nil {
		return x.DefaultVisibilityLevel
	}
	return VisibilityLevel_VISIBILITY_LEVEL_UNSPECIFIED
}

func (x *Project) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *Project) GetManager() *User {
	if x != nil {
		return x.Manager
	}
	return nil
}

func (x *Project) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

type CreateProjectRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Name                   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description            string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ManagerId              string                 `protobuf:"bytes,3,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	TenantId               string                 `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // Multi-tenancy
	DefaultVisibilityLevel VisibilityLevel        `protobuf:"varint,6,opt,name=default_visibility_level,json=defaultVisibilityLevel,proto3,enum=auth.VisibilityLevel" json:"default_visibility_level,omitempty"`
	Id                     string                 `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"` // Optional
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_auth_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_auth_project_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProjectRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProjectRequest) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *CreateProjectRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateProjectRequest) GetDefaultVisibilityLevel() VisibilityLevel {
	if x != nil {
		return x.DefaultVisibilityLevel
	}
	return VisibilityLevel_VISIBILITY_LEVEL_UNSPECIFIED
}

func (x *CreateProjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectResponse) Reset() {
	*x = CreateProjectResponse{}
	mi := &file_auth_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectResponse) ProtoMessage() {}

func (x *CreateProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectResponse.ProtoReflect.Descriptor instead.
func (*CreateProjectResponse) Descriptor() ([]byte, []int) {
	return file_auth_project_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProjectResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type BatchCreateProjectsRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	TenantId      string                  `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Requests      []*CreateProjectRequest `protobuf:"bytes,2,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateProjectsRequest) Reset() {
	*x = BatchCreateProjectsRequest{}
	mi := &file_auth_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateProjectsRequest) ProtoMessage() {}

func (x *BatchCreateProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateProjectsRequest.ProtoReflect.Descriptor instead.
func (*BatchCreateProjectsRequest) Descriptor() ([]byte, []int) {
	return file_auth_project_proto_rawDescGZIP(), []int{3}
}

func (x *BatchCreateProjectsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *BatchCreateProjectsRequest) GetRequests() []*CreateProjectRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type BatchCreateProjectsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SuccessCount   int32                  `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailureCount   int32                  `protobuf:"varint,2,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
	FailureReasons []string               `protobuf:"bytes,3,rep,name=failure_reasons,json=failureReasons,proto3" json:"failure_reasons,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchCreateProjectsResponse) Reset() {
	*x = BatchCreateProjectsResponse{}
	mi := &file_auth_project_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateProjectsResponse) ProtoMessage() {}

func (x *BatchCreateProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_project_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateProjectsResponse.ProtoReflect.Descriptor instead.
func (*BatchCreateProjectsResponse) Descriptor() ([]byte, []int) {
	return file_auth_project_proto_rawDescGZIP(), []int{4}
}

func (x *BatchCreateProjectsResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *BatchCreateProjectsResponse) GetFailureCount() int32 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

func (x *BatchCreateProjectsResponse) GetFailureReasons() []string {
	if x != nil {
		return x.FailureReasons
	}
	return nil
}

type ListProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SearchQuery   string                 `protobuf:"bytes,2,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"` // Optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_auth_project_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_project_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_auth_project_proto_rawDescGZIP(), []int{5}
}

func (x *ListProjectsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListProjectsRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

type ListProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_auth_project_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_project_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_auth_project_proto_rawDescGZIP(), []int{6}
}

func (x *ListProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

type UpdateProjectRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description            string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ManagerId              string                 `protobuf:"bytes,4,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	DefaultVisibilityLevel VisibilityLevel        `protobuf:"varint,6,opt,name=default_visibility_level,json=defaultVisibilityLevel,proto3,enum=auth.VisibilityLevel" json:"default_visibility_level,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UpdateProjectRequest) Reset() {
	*x = UpdateProjectRequest{}
	mi := &file_auth_project_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectRequest) ProtoMessage() {}

func (x *UpdateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_project_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectRequest.ProtoReflect.Descriptor instead.
func (*UpdateProjectRequest) Descriptor() ([]byte, []int) {
	return file_auth_project_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateProjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProjectRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProjectRequest) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *UpdateProjectRequest) GetDefaultVisibilityLevel() VisibilityLevel {
	if x != nil {
		return x.DefaultVisibilityLevel
	}
	return VisibilityLevel_VISIBILITY_LEVEL_UNSPECIFIED
}

type UpdateProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectResponse) Reset() {
	*x = UpdateProjectResponse{}
	mi := &file_auth_project_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectResponse) ProtoMessage() {}

func (x *UpdateProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_project_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectResponse.ProtoReflect.Descriptor instead.
func (*UpdateProjectResponse) Descriptor() ([]byte, []int) {
	return file_auth_project_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateProjectResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type DeleteProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectRequest) Reset() {
	*x = DeleteProjectRequest{}
	mi := &file_auth_project_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectRequest) ProtoMessage() {}

func (x *DeleteProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_project_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteProjectRequest) Descriptor() ([]byte, []int) {
	return file_auth_project_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteProjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectResponse) Reset() {
	*x = DeleteProjectResponse{}
	mi := &file_auth_project_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectResponse) ProtoMessage() {}

func (x *DeleteProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_project_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectResponse.ProtoReflect.Descriptor instead.
func (*DeleteProjectResponse) Descriptor() ([]byte, []int) {
	return file_auth_project_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteProjectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// GetProject used for details view
type GetProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectRequest) Reset() {
	*x = GetProjectRequest{}
	mi := &file_auth_project_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectRequest) ProtoMessage() {}

func (x *GetProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_project_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectRequest.ProtoReflect.Descriptor instead.
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return file_auth_project_proto_rawDescGZIP(), []int{11}
}

func (x *GetProjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectResponse) Reset() {
	*x = GetProjectResponse{}
	mi := &file_auth_project_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectResponse) ProtoMessage() {}

func (x *GetProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_project_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectResponse.ProtoReflect.Descriptor instead.
func (*GetProjectResponse) Descriptor() ([]byte, []int) {
	return file_auth_project_proto_rawDescGZIP(), []int{12}
}

func (x *GetProjectResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

// Reorder projects (drag-drop)
type ProjectOrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SortOrder     int32                  `protobuf:"varint,3,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectOrderItem) Reset() {
	*x = ProjectOrderItem{}
	mi := &file_auth_project_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectOrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectOrderItem) ProtoMessage() {}

func (x *ProjectOrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_auth_project_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectOrderItem.ProtoReflect.Descriptor instead.
func (*ProjectOrderItem) Descriptor() ([]byte, []int) {
	return file_auth_project_proto_rawDescGZIP(), []int{13}
}

func (x *ProjectOrderItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProjectOrderItem) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type ReorderProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Items         []*ProjectOrderItem    `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReorderProjectsRequest) Reset() {
	*x = ReorderProjectsRequest{}
	mi := &file_auth_project_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderProjectsRequest) ProtoMessage() {}

func (x *ReorderProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_project_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderProjectsRequest.ProtoReflect.Descriptor instead.
func (*ReorderProjectsRequest) Descriptor() ([]byte, []int) {
	return file_auth_project_proto_rawDescGZIP(), []int{14}
}

func (x *ReorderProjectsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ReorderProjectsRequest) GetItems() []*ProjectOrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReorderProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReorderProjectsResponse) Reset() {
	*x = ReorderProjectsResponse{}
	mi := &file_auth_project_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderProjectsResponse) ProtoMessage() {}

func (x *ReorderProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_project_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderProjectsResponse.ProtoReflect.Descriptor instead.
func (*ReorderProjectsResponse) Descriptor() ([]byte, []int) {
	return file_auth_project_proto_rawDescGZIP(), []int{15}
}

func (x *ReorderProjectsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_auth_project_proto protoreflect.FileDescriptor

const file_auth_project_proto_rawDesc = "" +
	"\n" +
	"\x12auth/project.proto\x12\x04auth\x1a\x0fauth/user.proto\x1a\x0eauth/acl.proto\"\xe5\x02\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x04 \x01(\tR\tmanagerId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12O\n" +
	"\x18default_visibility_level\x18\n" +
	" \x01(\x0e2\x15.auth.VisibilityLevelR\x16defaultVisibilityLevel\x12\x1d\n" +
	"\n" +
	"sort_order\x18\v \x01(\x05R\tsortOrder\x12$\n" +
	"\amanager\x18\b \x01(\v2\n" +
	".auth.UserR\amanager\x12!\n" +
	"\fmember_count\x18\t \x01(\x05R\vmemberCount\"\xe9\x01\n" +
	"\x14CreateProjectRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x03 \x01(\tR\tmanagerId\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\x12O\n" +
	"\x18default_visibility_level\x18\x06 \x01(\x0e2\x15.auth.VisibilityLevelR\x16defaultVisibilityLevel\x12\x0e\n" +
	"\x02id\x18\a \x01(\tR\x02id\"@\n" +
	"\x15CreateProjectResponse\x12'\n" +
	"\aproject\x18\x01 \x01(\v2\r.auth.ProjectR\aproject\"q\n" +
	"\x1aBatchCreateProjectsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x126\n" +
	"\brequests\x18\x02 \x03(\v2\x1a.auth.CreateProjectRequestR\brequests\"\x90\x01\n" +
	"\x1bBatchCreateProjectsResponse\x12#\n" +
	"\rsuccess_count\x18\x01 \x01(\x05R\fsuccessCount\x12#\n" +
	"\rfailure_count\x18\x02 \x01(\x05R\ffailureCount\x12'\n" +
	"\x0ffailure_reasons\x18\x03 \x03(\tR\x0efailureReasons\"U\n" +
	"\x13ListProjectsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12!\n" +
	"\fsearch_query\x18\x02 \x01(\tR\vsearchQuery\"A\n" +
	"\x14ListProjectsResponse\x12)\n" +
	"\bprojects\x18\x01 \x03(\v2\r.auth.ProjectR\bprojects\"\xcc\x01\n" +
	"\x14UpdateProjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x04 \x01(\tR\tmanagerId\x12O\n" +
	"\x18default_visibility_level\x18\x06 \x01(\x0e2\x15.auth.VisibilityLevelR\x16defaultVisibilityLevel\"@\n" +
	"\x15UpdateProjectResponse\x12'\n" +
	"\aproject\x18\x01 \x01(\v2\r.auth.ProjectR\aproject\"&\n" +
	"\x14DeleteProjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x15DeleteProjectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"#\n" +
	"\x11GetProjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"=\n" +
	"\x12GetProjectResponse\x12'\n" +
	"\aproject\x18\x01 \x01(\v2\r.auth.ProjectR\aproject\"A\n" +
	"\x10ProjectOrderItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x03 \x01(\x05R\tsortOrder\"c\n" +
	"\x16ReorderProjectsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12,\n" +
	"\x05items\x18\x02 \x03(\v2\x16.auth.ProjectOrderItemR\x05items\"3\n" +
	"\x17ReorderProjectsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccessB\x15Z\x13server/.protos/authb\x06proto3"

var (
	file_auth_project_proto_rawDescOnce sync.Once
	file_auth_project_proto_rawDescData []byte
)

func file_auth_project_proto_rawDescGZIP() []byte {
	file_auth_project_proto_rawDescOnce.Do(func() {
		file_auth_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_project_proto_rawDesc), len(file_auth_project_proto_rawDesc)))
	})
	return file_auth_project_proto_rawDescData
}

var file_auth_project_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_auth_project_proto_goTypes = []any{
	(*Project)(nil),                     // 0: auth.Project
	(*CreateProjectRequest)(nil),        // 1: auth.CreateProjectRequest
	(*CreateProjectResponse)(nil),       // 2: auth.CreateProjectResponse
	(*BatchCreateProjectsRequest)(nil),  // 3: auth.BatchCreateProjectsRequest
	(*BatchCreateProjectsResponse)(nil), // 4: auth.BatchCreateProjectsResponse
	(*ListProjectsRequest)(nil),         // 5: auth.ListProjectsRequest
	(*ListProjectsResponse)(nil),        // 6: auth.ListProjectsResponse
	(*UpdateProjectRequest)(nil),        // 7: auth.UpdateProjectRequest
	(*UpdateProjectResponse)(nil),       // 8: auth.UpdateProjectResponse
	(*DeleteProjectRequest)(nil),        // 9: auth.DeleteProjectRequest
	(*DeleteProjectResponse)(nil),       // 10: auth.DeleteProjectResponse
	(*GetProjectRequest)(nil),           // 11: auth.GetProjectRequest
	(*GetProjectResponse)(nil),          // 12: auth.GetProjectResponse
	(*ProjectOrderItem)(nil),            // 13: auth.ProjectOrderItem
	(*ReorderProjectsRequest)(nil),      // 14: auth.ReorderProjectsRequest
	(*ReorderProjectsResponse)(nil),     // 15: auth.ReorderProjectsResponse
	(VisibilityLevel)(0),                // 16: auth.VisibilityLevel
	(*User)(nil),                        // 17: auth.User
}
var file_auth_project_proto_depIdxs = []int32{
	16, // 0: auth.Project.default_visibility_level:type_name -> auth.VisibilityLevel
	17, // 1: auth.Project.manager:type_name -> auth.User
	16, // 2: auth.CreateProjectRequest.default_visibility_level:type_name -> auth.VisibilityLevel
	0,  // 3: auth.CreateProjectResponse.project:type_name -> auth.Project
	1,  // 4: auth.BatchCreateProjectsRequest.requests:type_name -> auth.CreateProjectRequest
	0,  // 5: auth.ListProjectsResponse.projects:type_name -> auth.Project
	16, // 6: auth.UpdateProjectRequest.default_visibility_level:type_name -> auth.VisibilityLevel
	0,  // 7: auth.UpdateProjectResponse.project:type_name -> auth.Project
	0,  // 8: auth.GetProjectResponse.project:type_name -> auth.Project
	13, // 9: auth.ReorderProjectsRequest.items:type_name -> auth.ProjectOrderItem
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_auth_project_proto_init() }
func file_auth_project_proto_init() {
	if File_auth_project_proto != nil {
		return
	}
	file_auth_user_proto_init()
	file_auth_acl_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_project_proto_rawDesc), len(file_auth_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_project_proto_goTypes,
		DependencyIndexes: file_auth_project_proto_depIdxs,
		MessageInfos:      file_auth_project_proto_msgTypes,
	}.Build()
	File_auth_project_proto = out.File
	file_auth_project_proto_goTypes = nil
	file_auth_project_proto_depIdxs = nil
}
