// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.31.1
// source: index/index.proto

package index

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IndexService_IndexDocument_FullMethodName     = "/index.IndexService/IndexDocument"
	IndexService_SearchDocuments_FullMethodName   = "/index.IndexService/SearchDocuments"
	IndexService_SyncDocuments_FullMethodName     = "/index.IndexService/SyncDocuments"
	IndexService_GenerateEmbedding_FullMethodName = "/index.IndexService/GenerateEmbedding"
	IndexService_GenerateDraft_FullMethodName     = "/index.IndexService/GenerateDraft"
)

// IndexServiceClient is the client API for IndexService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 인덱스 서비스 (IndexService) 정의
// 문서의 벡터화, 저장, 검색 및 동기화를 담당합니다.
type IndexServiceClient interface {
	// 문서 업로드 및 인덱싱 (벡터 생성 포함)
	IndexDocument(ctx context.Context, in *IndexDocumentRequest, opts ...grpc.CallOption) (*IndexDocumentResponse, error)
	// 문서 검색 (Semantic Search / RAG)
	SearchDocuments(ctx context.Context, in *SearchDocumentsRequest, opts ...grpc.CallOption) (*SearchDocumentsResponse, error)
	// 동기화: 클라이언트의 변경 사항(Delta)을 수신하고 충돌을 해결합니다.
	SyncDocuments(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SyncRequest, SyncResponse], error)
	// 임베딩 생성 (클라이언트 Local RAG용)
	GenerateEmbedding(ctx context.Context, in *GenerateEmbeddingRequest, opts ...grpc.CallOption) (*GenerateEmbeddingResponse, error)
	// 문서 초안 생성 (AI Draft Generation)
	// 사용자가 제공한 메타데이터와 참조 문서를 바탕으로 새 문서의 초안을 작성합니다.
	GenerateDraft(ctx context.Context, in *GenerateDraftRequest, opts ...grpc.CallOption) (*GenerateDraftResponse, error)
}

type indexServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIndexServiceClient(cc grpc.ClientConnInterface) IndexServiceClient {
	return &indexServiceClient{cc}
}

func (c *indexServiceClient) IndexDocument(ctx context.Context, in *IndexDocumentRequest, opts ...grpc.CallOption) (*IndexDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexDocumentResponse)
	err := c.cc.Invoke(ctx, IndexService_IndexDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexServiceClient) SearchDocuments(ctx context.Context, in *SearchDocumentsRequest, opts ...grpc.CallOption) (*SearchDocumentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchDocumentsResponse)
	err := c.cc.Invoke(ctx, IndexService_SearchDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexServiceClient) SyncDocuments(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SyncRequest, SyncResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IndexService_ServiceDesc.Streams[0], IndexService_SyncDocuments_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SyncRequest, SyncResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IndexService_SyncDocumentsClient = grpc.BidiStreamingClient[SyncRequest, SyncResponse]

func (c *indexServiceClient) GenerateEmbedding(ctx context.Context, in *GenerateEmbeddingRequest, opts ...grpc.CallOption) (*GenerateEmbeddingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateEmbeddingResponse)
	err := c.cc.Invoke(ctx, IndexService_GenerateEmbedding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexServiceClient) GenerateDraft(ctx context.Context, in *GenerateDraftRequest, opts ...grpc.CallOption) (*GenerateDraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateDraftResponse)
	err := c.cc.Invoke(ctx, IndexService_GenerateDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IndexServiceServer is the server API for IndexService service.
// All implementations must embed UnimplementedIndexServiceServer
// for forward compatibility.
//
// 인덱스 서비스 (IndexService) 정의
// 문서의 벡터화, 저장, 검색 및 동기화를 담당합니다.
type IndexServiceServer interface {
	// 문서 업로드 및 인덱싱 (벡터 생성 포함)
	IndexDocument(context.Context, *IndexDocumentRequest) (*IndexDocumentResponse, error)
	// 문서 검색 (Semantic Search / RAG)
	SearchDocuments(context.Context, *SearchDocumentsRequest) (*SearchDocumentsResponse, error)
	// 동기화: 클라이언트의 변경 사항(Delta)을 수신하고 충돌을 해결합니다.
	SyncDocuments(grpc.BidiStreamingServer[SyncRequest, SyncResponse]) error
	// 임베딩 생성 (클라이언트 Local RAG용)
	GenerateEmbedding(context.Context, *GenerateEmbeddingRequest) (*GenerateEmbeddingResponse, error)
	// 문서 초안 생성 (AI Draft Generation)
	// 사용자가 제공한 메타데이터와 참조 문서를 바탕으로 새 문서의 초안을 작성합니다.
	GenerateDraft(context.Context, *GenerateDraftRequest) (*GenerateDraftResponse, error)
	mustEmbedUnimplementedIndexServiceServer()
}

// UnimplementedIndexServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIndexServiceServer struct{}

func (UnimplementedIndexServiceServer) IndexDocument(context.Context, *IndexDocumentRequest) (*IndexDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IndexDocument not implemented")
}
func (UnimplementedIndexServiceServer) SearchDocuments(context.Context, *SearchDocumentsRequest) (*SearchDocumentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchDocuments not implemented")
}
func (UnimplementedIndexServiceServer) SyncDocuments(grpc.BidiStreamingServer[SyncRequest, SyncResponse]) error {
	return status.Error(codes.Unimplemented, "method SyncDocuments not implemented")
}
func (UnimplementedIndexServiceServer) GenerateEmbedding(context.Context, *GenerateEmbeddingRequest) (*GenerateEmbeddingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateEmbedding not implemented")
}
func (UnimplementedIndexServiceServer) GenerateDraft(context.Context, *GenerateDraftRequest) (*GenerateDraftResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateDraft not implemented")
}
func (UnimplementedIndexServiceServer) mustEmbedUnimplementedIndexServiceServer() {}
func (UnimplementedIndexServiceServer) testEmbeddedByValue()                      {}

// UnsafeIndexServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IndexServiceServer will
// result in compilation errors.
type UnsafeIndexServiceServer interface {
	mustEmbedUnimplementedIndexServiceServer()
}

func RegisterIndexServiceServer(s grpc.ServiceRegistrar, srv IndexServiceServer) {
	// If the following call panics, it indicates UnimplementedIndexServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IndexService_ServiceDesc, srv)
}

func _IndexService_IndexDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServiceServer).IndexDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexService_IndexDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServiceServer).IndexDocument(ctx, req.(*IndexDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexService_SearchDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServiceServer).SearchDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexService_SearchDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServiceServer).SearchDocuments(ctx, req.(*SearchDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexService_SyncDocuments_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IndexServiceServer).SyncDocuments(&grpc.GenericServerStream[SyncRequest, SyncResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IndexService_SyncDocumentsServer = grpc.BidiStreamingServer[SyncRequest, SyncResponse]

func _IndexService_GenerateEmbedding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateEmbeddingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServiceServer).GenerateEmbedding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexService_GenerateEmbedding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServiceServer).GenerateEmbedding(ctx, req.(*GenerateEmbeddingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexService_GenerateDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServiceServer).GenerateDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexService_GenerateDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServiceServer).GenerateDraft(ctx, req.(*GenerateDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IndexService_ServiceDesc is the grpc.ServiceDesc for IndexService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IndexService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "index.IndexService",
	HandlerType: (*IndexServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IndexDocument",
			Handler:    _IndexService_IndexDocument_Handler,
		},
		{
			MethodName: "SearchDocuments",
			Handler:    _IndexService_SearchDocuments_Handler,
		},
		{
			MethodName: "GenerateEmbedding",
			Handler:    _IndexService_GenerateEmbedding_Handler,
		},
		{
			MethodName: "GenerateDraft",
			Handler:    _IndexService_GenerateDraft_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SyncDocuments",
			Handler:       _IndexService_SyncDocuments_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "index/index.proto",
}
