// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: index/index.proto

package index

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 태그와 증거(근거 문장) 쌍
type TagEvidence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Evidence      string                 `protobuf:"bytes,2,opt,name=evidence,proto3" json:"evidence,omitempty"` // "chunk" -> "evidence"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagEvidence) Reset() {
	*x = TagEvidence{}
	mi := &file_index_index_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagEvidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagEvidence) ProtoMessage() {}

func (x *TagEvidence) ProtoReflect() protoreflect.Message {
	mi := &file_index_index_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagEvidence.ProtoReflect.Descriptor instead.
func (*TagEvidence) Descriptor() ([]byte, []int) {
	return file_index_index_proto_rawDescGZIP(), []int{0}
}

func (x *TagEvidence) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *TagEvidence) GetEvidence() string {
	if x != nil {
		return x.Evidence
	}
	return ""
}

// 문서 데이터 구조
type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                         // 문서 ID
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                                   // 제목
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`                               // 원문 전체 요약
	TagEvidences  []*TagEvidence         `protobuf:"bytes,4,rep,name=tag_evidences,json=tagEvidences,proto3" json:"tag_evidences,omitempty"` // 태그와 증거 목록
	OwnerId       string                 `protobuf:"bytes,5,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`                // 문서 소유자 ID (필수)
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`          // 수정 시간 (암호화된 문자열)
	UserSalt      string                 `protobuf:"bytes,7,opt,name=user_salt,json=userSalt,proto3" json:"user_salt,omitempty"`             // 암호화용 사용자 Salt
	Embedding     []float32              `protobuf:"fixed32,8,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`                  // 문서 임베딩 벡터
	GroupId       string                 `protobuf:"bytes,9,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`                // 소속 그룹 ID (Department/Project)
	GroupType     int32                  `protobuf:"varint,10,opt,name=group_type,json=groupType,proto3" json:"group_type,omitempty"`        // 그룹 타입 (0: Dept, 1: Project)
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`         // 생성 시간 (암호화된 문자열)
	Content       string                 `protobuf:"bytes,12,opt,name=content,proto3" json:"content,omitempty"`                              // 원문 내용 (임베딩 생성용)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_index_index_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_index_index_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_index_index_proto_rawDescGZIP(), []int{1}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Document) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Document) GetTagEvidences() []*TagEvidence {
	if x != nil {
		return x.TagEvidences
	}
	return nil
}

func (x *Document) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Document) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Document) GetUserSalt() string {
	if x != nil {
		return x.UserSalt
	}
	return ""
}

func (x *Document) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *Document) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *Document) GetGroupType() int32 {
	if x != nil {
		return x.GroupType
	}
	return 0
}

func (x *Document) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Document) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 인덱싱 요청
type IndexDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *Document              `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexDocumentRequest) Reset() {
	*x = IndexDocumentRequest{}
	mi := &file_index_index_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexDocumentRequest) ProtoMessage() {}

func (x *IndexDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_index_index_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexDocumentRequest.ProtoReflect.Descriptor instead.
func (*IndexDocumentRequest) Descriptor() ([]byte, []int) {
	return file_index_index_proto_rawDescGZIP(), []int{2}
}

func (x *IndexDocumentRequest) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

// 인덱싱 응답
type IndexDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DocumentId    string                 `protobuf:"bytes,3,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Embedding     []float32              `protobuf:"fixed32,4,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`                  // 생성된 임베딩 벡터 반환
	Summary       string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`                               // AI 생성 요약
	TagEvidences  []*TagEvidence         `protobuf:"bytes,6,rep,name=tag_evidences,json=tagEvidences,proto3" json:"tag_evidences,omitempty"` // AI 생성 태그+근거
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexDocumentResponse) Reset() {
	*x = IndexDocumentResponse{}
	mi := &file_index_index_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexDocumentResponse) ProtoMessage() {}

func (x *IndexDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_index_index_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexDocumentResponse.ProtoReflect.Descriptor instead.
func (*IndexDocumentResponse) Descriptor() ([]byte, []int) {
	return file_index_index_proto_rawDescGZIP(), []int{3}
}

func (x *IndexDocumentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IndexDocumentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *IndexDocumentResponse) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *IndexDocumentResponse) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *IndexDocumentResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *IndexDocumentResponse) GetTagEvidences() []*TagEvidence {
	if x != nil {
		return x.TagEvidences
	}
	return nil
}

// 검색 요청
type SearchDocumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`                       // 검색어 (자연어)
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                      // 최대 결과 수
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`                         // 태그 필터
	UserSalt      string                 `protobuf:"bytes,4,opt,name=user_salt,json=userSalt,proto3" json:"user_salt,omitempty"` // 암호화용 사용자 Salt
	OwnerId       string                 `protobuf:"bytes,5,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`    // 요청자 ID (자신 제외 검색용)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchDocumentsRequest) Reset() {
	*x = SearchDocumentsRequest{}
	mi := &file_index_index_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchDocumentsRequest) ProtoMessage() {}

func (x *SearchDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_index_index_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchDocumentsRequest.ProtoReflect.Descriptor instead.
func (*SearchDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_index_index_proto_rawDescGZIP(), []int{4}
}

func (x *SearchDocumentsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchDocumentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchDocumentsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SearchDocumentsRequest) GetUserSalt() string {
	if x != nil {
		return x.UserSalt
	}
	return ""
}

func (x *SearchDocumentsRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

// 검색 결과 항목
type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *Document              `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"` // 유사도 점수
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_index_index_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_index_index_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_index_index_proto_rawDescGZIP(), []int{5}
}

func (x *SearchResult) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *SearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

// 검색 응답
type SearchDocumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchDocumentsResponse) Reset() {
	*x = SearchDocumentsResponse{}
	mi := &file_index_index_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchDocumentsResponse) ProtoMessage() {}

func (x *SearchDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_index_index_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchDocumentsResponse.ProtoReflect.Descriptor instead.
func (*SearchDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_index_index_proto_rawDescGZIP(), []int{6}
}

func (x *SearchDocumentsResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// 동기화 요청
type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Changes       []*Document            `protobuf:"bytes,2,rep,name=changes,proto3" json:"changes,omitempty"` // 변경된 문서 목록
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_index_index_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_index_index_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_index_index_proto_rawDescGZIP(), []int{7}
}

func (x *SyncRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SyncRequest) GetChanges() []*Document {
	if x != nil {
		return x.Changes
	}
	return nil
}

// 동기화 응답
type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updates       []*Document            `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"` // 서버에서 클라이언트로 보낼 업데이트 (충돌 해결 후)
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_index_index_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_index_index_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_index_index_proto_rawDescGZIP(), []int{8}
}

func (x *SyncResponse) GetUpdates() []*Document {
	if x != nil {
		return x.Updates
	}
	return nil
}

func (x *SyncResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GenerateEmbeddingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateEmbeddingRequest) Reset() {
	*x = GenerateEmbeddingRequest{}
	mi := &file_index_index_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateEmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateEmbeddingRequest) ProtoMessage() {}

func (x *GenerateEmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_index_index_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateEmbeddingRequest.ProtoReflect.Descriptor instead.
func (*GenerateEmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_index_index_proto_rawDescGZIP(), []int{9}
}

func (x *GenerateEmbeddingRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type GenerateEmbeddingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embedding     []float32              `protobuf:"fixed32,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateEmbeddingResponse) Reset() {
	*x = GenerateEmbeddingResponse{}
	mi := &file_index_index_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateEmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateEmbeddingResponse) ProtoMessage() {}

func (x *GenerateEmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_index_index_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateEmbeddingResponse.ProtoReflect.Descriptor instead.
func (*GenerateEmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_index_index_proto_rawDescGZIP(), []int{10}
}

func (x *GenerateEmbeddingResponse) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

// 참조 문서 정보 (DraftReference)
// 초안 생성 시 AI가 참고할 문서나 웹 검색 결과입니다.
type DraftReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`     // 참조 문서 제목
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // 참조 내용 (요약본 혹은 발췌문)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DraftReference) Reset() {
	*x = DraftReference{}
	mi := &file_index_index_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DraftReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DraftReference) ProtoMessage() {}

func (x *DraftReference) ProtoReflect() protoreflect.Message {
	mi := &file_index_index_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DraftReference.ProtoReflect.Descriptor instead.
func (*DraftReference) Descriptor() ([]byte, []int) {
	return file_index_index_proto_rawDescGZIP(), []int{11}
}

func (x *DraftReference) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DraftReference) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 초안 생성 요청 (GenerateDraftRequest)
// 사용자가 입력한 정보를 바탕으로 AI에게 초안 작성을 요청하는 메시지입니다.
type GenerateDraftRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`                                      // 작성할 문서의 제목
	Tags          string                 `protobuf:"bytes,2,opt,name=tags,proto3" json:"tags,omitempty"`                                        // 관련 태그 (콤마로 구분된 문자열, 선택 사항)
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`                                  // 사용자가 작성한 요약 혹은 의도 (선택 사항)
	Template      string                 `protobuf:"bytes,4,opt,name=template,proto3" json:"template,omitempty"`                                // 사용할 템플릿 이름 (예: "Technical Specs")
	ReferenceDocs []*DraftReference      `protobuf:"bytes,5,rep,name=reference_docs,json=referenceDocs,proto3" json:"reference_docs,omitempty"` // 사용자가 선택한 로컬 참조 문서 목록
	WebResults    []*DraftReference      `protobuf:"bytes,6,rep,name=web_results,json=webResults,proto3" json:"web_results,omitempty"`          // 웹 검색 결과 목록
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateDraftRequest) Reset() {
	*x = GenerateDraftRequest{}
	mi := &file_index_index_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDraftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDraftRequest) ProtoMessage() {}

func (x *GenerateDraftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_index_index_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDraftRequest.ProtoReflect.Descriptor instead.
func (*GenerateDraftRequest) Descriptor() ([]byte, []int) {
	return file_index_index_proto_rawDescGZIP(), []int{12}
}

func (x *GenerateDraftRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GenerateDraftRequest) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *GenerateDraftRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *GenerateDraftRequest) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *GenerateDraftRequest) GetReferenceDocs() []*DraftReference {
	if x != nil {
		return x.ReferenceDocs
	}
	return nil
}

func (x *GenerateDraftRequest) GetWebResults() []*DraftReference {
	if x != nil {
		return x.WebResults
	}
	return nil
}

// 초안 생성 응답 (GenerateDraftResponse)
// AI가 작성한 마크다운 형식의 문서 초안입니다.
type GenerateDraftResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"` // 생성된 마크다운 내용
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateDraftResponse) Reset() {
	*x = GenerateDraftResponse{}
	mi := &file_index_index_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDraftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDraftResponse) ProtoMessage() {}

func (x *GenerateDraftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_index_index_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDraftResponse.ProtoReflect.Descriptor instead.
func (*GenerateDraftResponse) Descriptor() ([]byte, []int) {
	return file_index_index_proto_rawDescGZIP(), []int{13}
}

func (x *GenerateDraftResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_index_index_proto protoreflect.FileDescriptor

const file_index_index_proto_rawDesc = "" +
	"\n" +
	"\x11index/index.proto\x12\x05index\";\n" +
	"\vTagEvidence\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x1a\n" +
	"\bevidence\x18\x02 \x01(\tR\bevidence\"\xeb\x02\n" +
	"\bDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x127\n" +
	"\rtag_evidences\x18\x04 \x03(\v2\x12.index.TagEvidenceR\ftagEvidences\x12\x19\n" +
	"\bowner_id\x18\x05 \x01(\tR\aownerId\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x12\x1b\n" +
	"\tuser_salt\x18\a \x01(\tR\buserSalt\x12\x1c\n" +
	"\tembedding\x18\b \x03(\x02R\tembedding\x12\x19\n" +
	"\bgroup_id\x18\t \x01(\tR\agroupId\x12\x1d\n" +
	"\n" +
	"group_type\x18\n" +
	" \x01(\x05R\tgroupType\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x18\n" +
	"\acontent\x18\f \x01(\tR\acontent\"C\n" +
	"\x14IndexDocumentRequest\x12+\n" +
	"\bdocument\x18\x01 \x01(\v2\x0f.index.DocumentR\bdocument\"\xdd\x01\n" +
	"\x15IndexDocumentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vdocument_id\x18\x03 \x01(\tR\n" +
	"documentId\x12\x1c\n" +
	"\tembedding\x18\x04 \x03(\x02R\tembedding\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x127\n" +
	"\rtag_evidences\x18\x06 \x03(\v2\x12.index.TagEvidenceR\ftagEvidences\"\x90\x01\n" +
	"\x16SearchDocumentsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x1b\n" +
	"\tuser_salt\x18\x04 \x01(\tR\buserSalt\x12\x19\n" +
	"\bowner_id\x18\x05 \x01(\tR\aownerId\"Q\n" +
	"\fSearchResult\x12+\n" +
	"\bdocument\x18\x01 \x01(\v2\x0f.index.DocumentR\bdocument\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\"H\n" +
	"\x17SearchDocumentsResponse\x12-\n" +
	"\aresults\x18\x01 \x03(\v2\x13.index.SearchResultR\aresults\"U\n" +
	"\vSyncRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12)\n" +
	"\achanges\x18\x02 \x03(\v2\x0f.index.DocumentR\achanges\"S\n" +
	"\fSyncResponse\x12)\n" +
	"\aupdates\x18\x01 \x03(\v2\x0f.index.DocumentR\aupdates\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\".\n" +
	"\x18GenerateEmbeddingRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"9\n" +
	"\x19GenerateEmbeddingResponse\x12\x1c\n" +
	"\tembedding\x18\x01 \x03(\x02R\tembedding\"@\n" +
	"\x0eDraftReference\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xec\x01\n" +
	"\x14GenerateDraftRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04tags\x18\x02 \x01(\tR\x04tags\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x1a\n" +
	"\btemplate\x18\x04 \x01(\tR\btemplate\x12<\n" +
	"\x0ereference_docs\x18\x05 \x03(\v2\x15.index.DraftReferenceR\rreferenceDocs\x126\n" +
	"\vweb_results\x18\x06 \x03(\v2\x15.index.DraftReferenceR\n" +
	"webResults\"1\n" +
	"\x15GenerateDraftResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent2\x8e\x03\n" +
	"\fIndexService\x12J\n" +
	"\rIndexDocument\x12\x1b.index.IndexDocumentRequest\x1a\x1c.index.IndexDocumentResponse\x12P\n" +
	"\x0fSearchDocuments\x12\x1d.index.SearchDocumentsRequest\x1a\x1e.index.SearchDocumentsResponse\x12<\n" +
	"\rSyncDocuments\x12\x12.index.SyncRequest\x1a\x13.index.SyncResponse(\x010\x01\x12V\n" +
	"\x11GenerateEmbedding\x12\x1f.index.GenerateEmbeddingRequest\x1a .index.GenerateEmbeddingResponse\x12J\n" +
	"\rGenerateDraft\x12\x1b.index.GenerateDraftRequest\x1a\x1c.index.GenerateDraftResponseB\x16Z\x14server/.protos/indexb\x06proto3"

var (
	file_index_index_proto_rawDescOnce sync.Once
	file_index_index_proto_rawDescData []byte
)

func file_index_index_proto_rawDescGZIP() []byte {
	file_index_index_proto_rawDescOnce.Do(func() {
		file_index_index_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_index_index_proto_rawDesc), len(file_index_index_proto_rawDesc)))
	})
	return file_index_index_proto_rawDescData
}

var file_index_index_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_index_index_proto_goTypes = []any{
	(*TagEvidence)(nil),               // 0: index.TagEvidence
	(*Document)(nil),                  // 1: index.Document
	(*IndexDocumentRequest)(nil),      // 2: index.IndexDocumentRequest
	(*IndexDocumentResponse)(nil),     // 3: index.IndexDocumentResponse
	(*SearchDocumentsRequest)(nil),    // 4: index.SearchDocumentsRequest
	(*SearchResult)(nil),              // 5: index.SearchResult
	(*SearchDocumentsResponse)(nil),   // 6: index.SearchDocumentsResponse
	(*SyncRequest)(nil),               // 7: index.SyncRequest
	(*SyncResponse)(nil),              // 8: index.SyncResponse
	(*GenerateEmbeddingRequest)(nil),  // 9: index.GenerateEmbeddingRequest
	(*GenerateEmbeddingResponse)(nil), // 10: index.GenerateEmbeddingResponse
	(*DraftReference)(nil),            // 11: index.DraftReference
	(*GenerateDraftRequest)(nil),      // 12: index.GenerateDraftRequest
	(*GenerateDraftResponse)(nil),     // 13: index.GenerateDraftResponse
}
var file_index_index_proto_depIdxs = []int32{
	0,  // 0: index.Document.tag_evidences:type_name -> index.TagEvidence
	1,  // 1: index.IndexDocumentRequest.document:type_name -> index.Document
	0,  // 2: index.IndexDocumentResponse.tag_evidences:type_name -> index.TagEvidence
	1,  // 3: index.SearchResult.document:type_name -> index.Document
	5,  // 4: index.SearchDocumentsResponse.results:type_name -> index.SearchResult
	1,  // 5: index.SyncRequest.changes:type_name -> index.Document
	1,  // 6: index.SyncResponse.updates:type_name -> index.Document
	11, // 7: index.GenerateDraftRequest.reference_docs:type_name -> index.DraftReference
	11, // 8: index.GenerateDraftRequest.web_results:type_name -> index.DraftReference
	2,  // 9: index.IndexService.IndexDocument:input_type -> index.IndexDocumentRequest
	4,  // 10: index.IndexService.SearchDocuments:input_type -> index.SearchDocumentsRequest
	7,  // 11: index.IndexService.SyncDocuments:input_type -> index.SyncRequest
	9,  // 12: index.IndexService.GenerateEmbedding:input_type -> index.GenerateEmbeddingRequest
	12, // 13: index.IndexService.GenerateDraft:input_type -> index.GenerateDraftRequest
	3,  // 14: index.IndexService.IndexDocument:output_type -> index.IndexDocumentResponse
	6,  // 15: index.IndexService.SearchDocuments:output_type -> index.SearchDocumentsResponse
	8,  // 16: index.IndexService.SyncDocuments:output_type -> index.SyncResponse
	10, // 17: index.IndexService.GenerateEmbedding:output_type -> index.GenerateEmbeddingResponse
	13, // 18: index.IndexService.GenerateDraft:output_type -> index.GenerateDraftResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_index_index_proto_init() }
func file_index_index_proto_init() {
	if File_index_index_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_index_index_proto_rawDesc), len(file_index_index_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_index_index_proto_goTypes,
		DependencyIndexes: file_index_index_proto_depIdxs,
		MessageInfos:      file_index_index_proto_msgTypes,
	}.Build()
	File_index_index_proto = out.File
	file_index_index_proto_goTypes = nil
	file_index_index_proto_depIdxs = nil
}
